import 'dart:convert';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:sunmi_printer_plus/sunmi_printer_plus.dart';

class PrinterBase {
  static String formatCurrency(double amount) {
    return amount.toStringAsFixed(3);
  }

  static String formatQuantity(double qty, String unit) {
    if (qty == qty.roundToDouble()) {
      return '${qty.toInt()} $unit';
    }
    return '${qty.toStringAsFixed(2)} $unit';
  }

  static String getSeparator(int paperSize) {
    return '=' * (paperSize == 80 ? 48 : 32);
  }

  static String getDashedSeparator(int paperSize) {
    return '-' * (paperSize == 80 ? 48 : 32);
  }

  static String getCurrencySymbol(Map<String, dynamic>? companySettings, {bool isArabic = true}) {
    final rawCurrency = companySettings?['CurrencySymbol']?.toString() ?? '';
    if (rawCurrency.isEmpty) return isArabic ? 'د.ك' : 'KWD';
    return rawCurrency;
  }

  /// Robust product name resolver checking all possible API/Database keys
  static String getProductName(dynamic item, {bool isArabic = true}) {
    if (item is! Map) return isArabic ? 'منتج' : 'Item';

    final dynamic nameVal = item['name'] ??
        item['Name'] ??
        item['product_name'] ??
        item['ProductName'] ??
        item['ItemName'] ??
        item['item_name'] ??
        item['productName'] ??
        (isArabic ? (item['name_ar'] ?? item['name_en']) : (item['name_en'] ?? item['name_ar'])) ??
        item['description'] ??
        item['Description'];

    if (nameVal != null && nameVal.toString().trim().isNotEmpty) {
      return nameVal.toString().trim();
    }
    return isArabic ? 'منتج' : 'Item';
  }

  /// Converts RGBA pixels generated by ui.Canvas to ESC/POS monochrome raster bytes (GS v 0)
  static List<int> convertRgbaToRasterBytes(Uint8List rgbaBytes, int width, int height) {
    final List<int> bytes = [];
    final int widthInBytes = (width + 7) ~/ 8;

    // ESC @ (Initialize Printer)
    bytes.addAll([0x1B, 0x40]);

    // GS v 0 mode 0 xL xH yL yH
    bytes.addAll([0x1D, 0x76, 0x30, 0x00]);
    bytes.add(widthInBytes % 256);
    bytes.add(widthInBytes ~/ 256);
    bytes.add(height % 256);
    bytes.add(height ~/ 256);

    for (int y = 0; y < height; y++) {
      for (int xByte = 0; xByte < widthInBytes; xByte++) {
        int byteVal = 0;
        for (int bit = 0; bit < 8; bit++) {
          final int pixelX = xByte * 8 + bit;
          if (pixelX < width) {
            final int rgbaIndex = (y * width + pixelX) * 4;
            final int r = rgbaBytes[rgbaIndex];
            final int g = rgbaBytes[rgbaIndex + 1];
            final int b = rgbaBytes[rgbaIndex + 2];
            final int a = rgbaBytes[rgbaIndex + 3];

            // Black pixel if alpha > 128 and luminance < 180
            final double luminance = (0.299 * r) + (0.587 * g) + (0.114 * b);
            if (a > 128 && luminance < 180) {
              byteVal |= (0x80 >> bit);
            }
          }
        }
        bytes.add(byteVal);
      }
    }

    // Feed 4 lines & Cut
    bytes.addAll([0x1B, 0x64, 0x04]);
    bytes.addAll([0x1D, 0x56, 0x42, 0x00]);
    return bytes;
  }

  /// Converts a base64 encoded image to ESC/POS raster format (GS v 0) for network printers.
  static Future<List<int>> convertImageToEscPos(String base64Image, {int targetWidth = 200}) async {
    try {
      final String cleanBase64 = base64Image.contains(',') ? base64Image.split(',').last : base64Image;
      final Uint8List imageBytes = base64Decode(cleanBase64);

      final ui.Codec codec = await ui.instantiateImageCodec(imageBytes);
      final ui.FrameInfo fi = await codec.getNextFrame();
      final ui.Image image = fi.image;

      final double aspectRatio = image.height / image.width;
      final int targetHeight = (targetWidth * aspectRatio).round();

      final ui.PictureRecorder recorder = ui.PictureRecorder();
      final ui.Canvas canvas = ui.Canvas(recorder);

      canvas.drawImageRect(
        image,
        ui.Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()),
        ui.Rect.fromLTWH(0, 0, targetWidth.toDouble(), targetHeight.toDouble()),
        ui.Paint()..filterQuality = ui.FilterQuality.high,
      );

      final ui.Picture picture = recorder.endRecording();
      final ui.Image resizedImage = await picture.toImage(targetWidth, targetHeight);

      final ByteData? byteData = await resizedImage.toByteData(format: ui.ImageByteFormat.rawRgba);
      if (byteData == null) return [];

      final Uint8List rgbaBytes = byteData.buffer.asUint8List();
      final int widthInBytes = (targetWidth + 7) ~/ 8;

      final List<int> escPosBytes = [];
      escPosBytes.addAll([0x1B, 0x40]); // ESC @
      escPosBytes.addAll([0x1B, 0x61, 0x01]); // Align Center

      escPosBytes.addAll([0x1D, 0x76, 0x30, 0x00]); // GS v 0 0
      escPosBytes.add(widthInBytes % 256);
      escPosBytes.add(widthInBytes ~/ 256);
      escPosBytes.add(targetHeight % 256);
      escPosBytes.add(targetHeight ~/ 256);

      for (int y = 0; y < targetHeight; y++) {
        for (int xByte = 0; xByte < widthInBytes; xByte++) {
          int byteVal = 0;
          for (int bit = 0; bit < 8; bit++) {
            final int pixelX = xByte * 8 + bit;
            if (pixelX < targetWidth) {
              final int rgbaIndex = (y * targetWidth + pixelX) * 4;
              final int r = rgbaBytes[rgbaIndex];
              final int g = rgbaBytes[rgbaIndex + 1];
              final int b = rgbaBytes[rgbaIndex + 2];
              final int a = rgbaBytes[rgbaIndex + 3];

              final double luminance = (0.299 * r) + (0.587 * g) + (0.114 * b);
              if (a > 128 && luminance < 180) {
                byteVal |= (0x80 >> bit);
              }
            }
          }
          escPosBytes.add(byteVal);
        }
      }

      escPosBytes.addAll([0x1B, 0x61, 0x00]); // Align Left
      escPosBytes.addAll([0x1B, 0x64, 0x02]); // Feed 2 lines

      return escPosBytes;
    } catch (e) {
      if (kDebugMode) print('Error converting image to ESC/POS: $e');
      return [];
    }
  }

  /// ESC/POS Cash Drawer kick pulse command (ESC p m t1 t2 -> 0x1B, 0x70, 0x00, 0x19, 0xFA)
  static List<int> getDrawerKickBytes() {
    return [0x1B, 0x70, 0x00, 0x19, 0xFA];
  }

  /// Open Sunmi Cash Drawer safely (for internal Sunmi hardware printer)
  static Future<void> openSunmiDrawer() async {
    try {
      await SunmiPrinter.printRawData(Uint8List.fromList(getDrawerKickBytes()));
    } catch (e) {
      if (kDebugMode) print('Error opening Sunmi cash drawer: $e');
    }
  }
}
