import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'الإعدادات العامة',
      'home': 'الرئيسية',
      // Login Screen
      'login_title': 'تسجيل الدخول',
      'login_username_hint': 'اسم المستخدم',
      'login_password_hint': 'كلمة المرور',
      'login_button': 'دخول',
      'login_empty_error': 'يرجى إدخال اسم المستخدم وكلمة المرور',
      'login_failed_fallback': 'فشل تسجيل الدخول',
      // License Screen
      'license_whatsapp_error':
          'تعذر فتح تطبيق WhatsApp، يرجى مراسلة الرقم 55381505 يدوياً',
      'license_copied': 'تم نسخ بصمة الجهاز إلى الحافظة بنجاح!',
      'license_title': 'حماية Vegtablity POS',
      'license_checking': 'جاري التحقق من ترخيص هذا الجهاز...',
      'license_expired_title': 'انتهت صلاحية الاشتراك!',
      'license_expired_desc':
          'نأسف، لقد انتهت صلاحية اشتراك هذا الجهاز بتاريخ ',
      'license_expired_desc_2':
          '.\nيرجى تجديد الاشتراك مع الدعم الفني للاستمرار في العمل.',
      'license_error_title': 'خطأ في الاتصال!',
      'license_inactive_title': 'الترخيص غير نشط!',
      'license_inactive_desc':
          'هذا الجهاز مسجل لدينا ولكن تم إيقاف الترخيص مؤقتاً.\nيرجى مراجعة الدعم الفني لتفعيل صلاحية الدخول.',
      'license_unregistered_title': 'الجهاز غير مسجل!',
      'license_unregistered_desc':
          'رقم هوية هذا الجهاز غير مسجل في نظام التراخيص الخاص بنا.\nيرجى إرسال بصمة الجهاز للدعم الفني لتسجيله وتفعيله.',
      'license_hwid_label': 'بصمة الجهاز الخاصة بك',
      'license_support_title': 'الدعم الفني والترخيص',
      'license_phone_label': 'هاتف:',
      'license_send_whatsapp': 'إرسال البصمة عبر WhatsApp',
      'license_info_button': 'بيانات توضيحية',
      'license_retry_button': 'إعادة التحقق',
      // Shift Screen
      'shift_open_error_empty': 'يرجى إدخال مبلغ عهدة افتتاحية صحيح',
      'shift_open_failed_fallback': 'فشل فتح الوردية',
      'shift_checking_status': 'جاري التحقق من حالة الوردية...',
      'shift_wait_data': 'يرجى الانتظار لحين تحميل البيانات من السيرفر',
      'shift_new_title': 'فتح وردية جديدة',
      'shift_confirm_cash': 'تأكيد العهدة الافتتاحية للكاشير',
      'shift_cash_label': 'الرقم (الكاش)',
      'shift_open_button': 'فتح الوردية وبدء العمل',
      // Home Screen
      'home_title': 'نظام الكاشير الذكي (POS)',
      'home_server_status': 'حالة السيرفر: ',
      'home_welcome': 'مرحباً: ',
      'home_developed_by': 'Developed by Mohamed Ragab',
      'home_printer_settings': 'إعدادات الطابعة الحرارية',
      'home_daily_invoices': 'تقرير الفواتير اليومية',
      'home_close_shift': 'إغلاق الوردية',
      'home_receipt_voucher': 'سند قبض',
      'home_receipt_voucher_sub': 'تحصيل إيرادات (مباشر)',
      'home_payment_voucher': 'سند صرف',
      'home_payment_voucher_sub': 'سداد مصروفات (مباشر)',
      'home_logout': 'تسجيل الخروج',
      'home_offline_invoices_1': 'لديك ',
      'home_offline_invoices_2':
          ' فاتورة/فواتير محفوظة محلياً بانتظار المزامنة.',
      'home_sync_success': 'تمت المزامنة',
      'home_sync_failed': 'فشلت المزامنة',
      'home_sync_now': 'مزامنة الآن',
      'home_offline_vouchers_2': ' سند/سندات محفوظة محلياً بانتظار المزامنة.',
      'home_sync': 'مزامنة',
      'home_classic_new_invoice': 'فاتورة مبيعات جديدة',
      'home_classic_manage_partners': 'إدارة الموردين/العملاء',
      'home_classic_sales_quote': 'استدعاء عرض مبيعات',
      'home_premium_customer_sales': 'مبيعات العملاء',
      'home_premium_supplier_purchases': 'مشتريات الموردين',
      'home_premium_customer_receipts': 'تحصيل العملاء',
      'home_premium_receipts_sub': 'سندات قبض',
      'home_premium_supplier_payments': 'دفع الموردين',
      'home_premium_payments_sub': 'سندات صرف',
      // Settings Screen
      'settings_save_success':
          'تم حفظ النمط الجديد وتحديث واجهة الشاشة الرئيسية بنجاح',
      'settings_save_error': 'حدث خطأ أثناء حفظ الإعدادات يرجى المحاولة لاحقاً',
      'settings_layout_title': 'مظهر وتصميم الشاشة الرئيسية',
      'settings_layout_desc':
          'اختر الواجهة التي ترغب بالعمل عليها. يتم تحميل التفضيل تلقائياً عند بدء التشغيل.',
      'settings_classic_title': 'النمط الكلاسيكي (الافتراضي)',
      'settings_classic_desc':
          'الواجهة الأصلية التي تتيح الوصول السريع لعمليات البيع اليدوية المباشرة وإدارة الموردين واستدعاء العروض العامة.',
      'settings_premium_title': 'نمط عروض الشركاء (الجديد)',
      'settings_premium_desc':
          'واجهة POS مخصصة بالكامل لعروض أسعار الشركاء النشطة (مشتريات/مبيعات)، تمنع إدخال منتجات خارج العرض وتدعم الدفع كاش أو آجل.',
      // POS Screen
      'pos_barcode_simulator_title': 'محاكي قارئ الباركود والمنتجات',
      'pos_barcode_simulator_input': 'أدخل الباركود أو اسم المنتج',
      'pos_cancel': 'إلغاء',
      'pos_add_to_cart': 'إضافة للسلة',
      'pos_sales_title': 'نقطة بيع',
      'pos_purchases_title': 'فاتورة مشتريات',
      'pos_barcode_input': 'إدخال الباركود أو اسم المنتج يدوياً',
      'pos_empty_cart':
          'السلة فارغة. قم بمسح أو إدخال باركود المنتجات بدءاً بالعمل.',
      'pos_item_price': 'السعر: ',
      'pos_item_quantity': ' | الكمية: ',
      'pos_save_success_warn':
          'تم إضافة الفاتورة رقم ({id}) ولكن فشل الاتصال بالطابعة',
      'pos_save_success_ok': 'تمت الإضافة والطباعة للفاتورة رقم ({id})',
      'pos_print_status_printed': 'طُبعت',
      'pos_print_status_virtual': 'افتراضية',
      'pos_print_status_failed': 'فشل الطباعة',
      'pos_save_failed': 'فشل في حفظ الفاتورة',
      'pos_total': 'الإجمالي',
      'pos_pay_print': 'دفع وطباعة (F12)',
      // Partner Offers Screen
      'po_error_fetch_partners': 'فشل استرجاع بيانات الشركاء النشطين',
      'po_error_network': 'حدث خطأ في الاتصال بالشبكة: ',
      'po_loading_quote': 'جاري تحميل تفاصيل العرض والأسعار المعتمدة...',
      'po_no_active_quote':
          'لا يوجد عرض أسعار نشط أو معتمد لهذا الشريك حالياً!',
      'po_error_loading_quote': 'حدث خطأ أثناء تحميل العرض: ',
      'po_sales_partners_title': 'عملاء عروض المبيعات النشطة',
      'po_purchases_partners_title': 'موردي عروض المشتريات النشطة',
      'po_search_hint': 'ابحث باسم الشريك أو رقم الهاتف...',
      'po_retry': 'إعادة المحاولة',
      'po_no_partners_found': 'لا يوجد شركاء نشطين متطابقين للبحث حالياً.',
      'po_no_phone': 'لا يوجد هاتف',
      'po_no_address': 'العنوان غير محدد',
      // Partner Billing Screen
      'pb_unknown_item': 'صنف غير معروف',
      'pb_item_piece': 'حبة',
      'pb_item_added': 'تم إضافة: ',
      'pb_alert_unapproved': 'تنبيه - صنف غير معتمد',
      'pb_alert_unapproved_desc':
          'الباركود ({barcode}) غير مدرج في عرض الأسعار النشط والعتمد لهذا الشريك!\n\nيُمنع إضافة منتجات من خارج العرض.',
      'pb_ok': 'موافق',
      'pb_scan_camera_title': 'مسح الباركود بالكاميرا',
      'pb_scan_camera_hint': 'وجه الكاميرا نحو باركود الصنف',
      'pb_cart_empty_error': 'السلة فارغة! يرجى إضافة منتجات أولاً',
      'pb_offer_notes': 'فاتورة عروض شركاء - عرض رقم ',
      'pb_save_success':
          'تم إضافة الفاتورة رقم ({id}) بنجاح وإرسال أمر الطباعة.',
      'pb_save_server_fail': 'فشل حفظ الفاتورة على السيرفر: ',
      'pb_network_error': 'خطأ في الاتصال بالشبكة: ',
      'pb_sales_offer_invoice': 'فاتورة مبيعات عروض',
      'pb_purchase_offer_invoice': 'فاتورة مشتريات عروض',
      'pb_partner_name': 'الشريك: ',
      'pb_scan_tooltip': 'مسح باركود بالكاميرا',
      'pb_items_in_cart': 'الأصناف في السلة: ',
      'pb_total_kd': 'الإجمالي: {total} د.ك',
      'pb_search_hint': 'ابحث باسم المنتج أو الباركود...',
      'pb_barcode_hint': 'أدخل الباركود...',
      'pb_approved_items_title': 'الأصناف والأسعار المعتمدة داخل عرض الشريك:',
      'pb_no_barcode': 'بلا باركود',
      'pb_cart_title': 'سلة المشتريات / الفاتورة الحالية',
      'pb_cart_empty': 'السلة فارغة\nانقر على الأصناف لإضافتها',
      'pb_item_price': 'السعر: ',
      'pb_item_quantity': ' د.ك | الكمية: ',
      'pb_subtotal': 'الإجمالي الفرعي:',
      'pb_discount_value': 'قيمة الخصم:',
      'pb_net_amount': 'الصافي النهائي:',
      'pb_pay_cash': 'حفظ كاش (F12)',
      'pb_pay_credit': 'حفظ آجل (Credit)',
      'pb_no_results': 'لا توجد نتائج مطابقة للبحث',
      'pb_add_btn': 'إضافة',
      'pb_view_cart': 'عرض السلة ({count})',
      'pb_current_cart': 'محتويات السلة الحالية:',
      'pb_empty_cart_short': 'السلة فارغة',
      'pb_final_net': 'الإجمالي النهائي الصافي: {total} د.ك',
      // Payment Voucher Screen
      'pv_offline_error': 'أنت في وضع عدم الاتصال. يمكن إدخال سداد حر.',
      'pv_supplier_required': 'يرجى اختيار مورد أولاً',
      'pv_invoice_or_free_required':
          'يرجى اختيار فاتورة واحدة على الأقل أو إدخال مبلغ سداد حر',
      'pv_account_required': 'يرجى اختيار حساب الصرف',
      'pv_no_shift_open': 'لا توجد وردية مفتوحة',
      'pv_confirm_title': 'تأكيد سند الصرف',
      'pv_confirm_desc':
          'سيتم تسجيل سند صرف بقيمة\n{amount} د.ك\nللمورد: {partner}',
      'pv_cancel': 'إلغاء',
      'pv_confirm': 'تأكيد',
      'pv_default_desc': 'سند صرف - ',
      'pv_save_print_success': 'تم الحفظ والطباعة للسند رقم ({id})',
      'pv_save_error': 'خطأ غير متوقع: ',
      'pv_screen_title': 'سند صرف',
      'pv_supplier_label': 'المورد: ',
      'pv_search_hint': 'بحث عن مورد بالاسم أو الهاتف...',
      'pv_no_suppliers': 'لا يوجد موردون',
      'pv_no_dues': 'لا توجد مستحقات لهذا المورد',
      'pv_account_label': 'حساب الصرف',
      'pv_note_hint': 'ملاحظة (اختياري)...',
      'pv_no_invoices':
          'لا توجد فواتير (أو لا يوجد اتصال).\nيمكنك إدخال سداد حر (دفعة من الحساب).',
      'pv_free_payment_label': 'مبلغ الدفعة الحرة (سداد من الحساب)',
      'pv_purchase_invoice_label': 'فاتورة مشتريات #',
      'pv_total_label': 'الإجمالي: ',
      'pv_remainder_label': 'المتبقي: {amount} د.ك',
      'pv_payment_amount_label': 'مبلغ الصرف: ',
      'pv_selected_invoices': '{count} فاتورة محددة',
      'pv_submit_button': 'تسجيل الصرف',
      // Receipt Voucher Screen
      'rv_offline_error': 'أنت في وضع عدم الاتصال. لا يمكن جلب الفواتير. يرجى إدخال مبلغ السداد الحر.',
      'rv_customer_required': 'يرجى اختيار عميل أولاً',
      'rv_invoice_or_free_required': 'يرجى اختيار فاتورة واحدة على الأقل أو إدخال مبلغ سداد حر',
      'rv_account_required': 'يرجى اختيار حساب القبض',
      'rv_no_shift_open': 'لا توجد وردية مفتوحة',
      'rv_confirm_title': 'تأكيد سند القبض',
      'rv_confirm_desc': 'سيتم تسجيل سند قبض بقيمة\n{amount} د.ك\nمن العميل: {partner}',
      'rv_cancel': 'إلغاء',
      'rv_confirm': 'تأكيد',
      'rv_default_desc': 'سند قبض - ',
      'rv_save_print_success': 'تم الحفظ والطباعة للسند رقم ({id})',
      'rv_save_error': 'خطأ غير متوقع: ',
      'rv_screen_title': 'سند قبض',
      'rv_customer_label': 'العميل: ',
      'rv_search_hint': 'بحث عن عميل بالاسم أو الهاتف...',
      'rv_no_customers': 'لا يوجد عملاء',
      'rv_no_dues': 'لا توجد فواتير مستحقة لهذا العميل',
      'rv_account_label': 'حساب القبض',
      'rv_note_hint': 'ملاحظة (اختياري)...',
      'rv_no_invoices': 'لا يمكن جلب الفواتير (أو لا توجد فواتير).\nيمكنك إدخال سداد حر (دفعة من الحساب).',
      'rv_free_payment_label': 'مبلغ الدفعة الحرة (سداد من الحساب)',
      'rv_sales_invoice_label': 'فاتورة رقم #',
      'rv_total_label': 'الإجمالي: ',
      'rv_remainder_label': 'المتبقي: {amount} د.ك',
      'rv_receipt_amount_label': 'مبلغ السداد: ',
      'rv_selected_invoices': '{count} فاتورة محددة',
      'rv_submit_button': 'تسجيل القبض',
      // General Payment Voucher Screen
      'gpv_choose_expense_account': 'اختر حساب المصروفات',
      'gpv_search_account_hint': 'ابحث عن حساب...',
      'gpv_account_code': 'كود: {code}',
      'gpv_expense_account_required': 'الرجاء اختيار الحساب المستهدف (المصروفات)',
      'gpv_amount_required': 'الرجاء إدخال المبلغ',
      'gpv_invalid_amount': 'المبلغ غير صحيح',
      'gpv_cash_account_required': 'الرجاء اختيار حساب الصندوق/البنك',
      'gpv_undefined': 'غير محدد',
      'gpv_cash': 'نقدي',
      'gpv_save_print_success': 'تم إنشاء وطباعة سند الصرف بنجاح (رقم {id})',
      'gpv_save_error': 'حدث خطأ أثناء الحفظ: ',
      'gpv_cannot_save': 'تعذر الحفظ: ',
      'gpv_screen_title': 'سند صرف مباشر (مصروفات)',
      'gpv_target_account_label': 'الحساب المستهدف (المصروف)',
      'gpv_click_to_choose': 'اضغط لاختيار الحساب',
      'gpv_amount_label': 'المبلغ (د.ك)',
      'gpv_statement_label': 'البيان / الملاحظات',
      'gpv_pay_from_account': 'دفع من حساب (الصندوق)',
      'gpv_save_button': 'حفظ السند المباشر',
      // General Receipt Voucher Screen
      'grv_choose_revenue_account': 'اختر حساب الإيرادات',
      'grv_revenue_account_required': 'الرجاء اختيار الحساب المستهدف (الإيرادات)',
      'grv_save_print_success': 'تم إنشاء وطباعة سند القبض بنجاح (رقم {id})',
      'grv_screen_title': 'سند قبض مباشر (إيرادات)',
      'grv_target_account_label': 'الحساب المستهدف (الإيراد)',
      'grv_receive_to_account': 'قبض إلى حساب (الصندوق)',
      'grv_save_button': 'حفظ السند المباشر',
      // Daily Invoices Screen
      'di_fetch_error': 'فشل استرجاع فواتير اليوم من الخادم',
      'di_error_loading': 'حدث خطأ أثناء تحميل الفواتير: {error}',
      'di_screen_title': 'تقرير الفواتير اليومية والمستخدم',
      'di_total_sales': 'إجمالي المبيعات',
      'di_total_purchases': 'إجمالي المشتريات',
      'di_net_income': 'صافي الدخل (مبيعات - مشتريات)',
      'di_total_receipts': 'سندات قبض (وارد)',
      'di_total_payments': 'سندات صرف (صادر)',
      'di_net_cash': 'صافي النقدية (الدرج)',
      'di_tab_sales': 'المبيعات',
      'di_tab_purchases': 'المشتريات',
      'di_tab_receipts': 'سندات القبض',
      'di_tab_payments': 'سندات الصرف',
      'di_sales_invoices': 'مبيعات العملاء اليومية',
      'di_purchase_invoices': 'مشتريات الموردين اليومية',
      'di_receipt_vouchers': 'سندات القبض (محصلات)',
      'di_payment_vouchers': 'سندات الصرف (مدفوعات)',
      'di_daily_financial_split': 'الفصل المالي اليومي',
      'di_shift_financial_vouchers': 'السندات المالية للوردية',
      'di_no_invoices': 'لا توجد بيانات',
      'di_invoice_no': 'رقم الفاتورة: #{id}',
      'di_date': 'التاريخ: {date}',
      'di_time': 'الوقت: {time}',
      'di_net_amount': 'الصافي: {amount} د.ك',
      'di_voucher_no': 'رقم السند: #{id}',
      'di_voucher_amount': 'المبلغ: {amount} د.ك',
      'di_voucher_desc': 'البيان: {desc}',
      'di_print_button': 'طباعة التفاصيل',
      'di_print_success': 'تمت طباعة الفاتورة بنجاح',
      'di_print_error': 'فشل في طباعة الفاتورة',
      'di_invoice_details': 'تفاصيل الفاتورة',
      'di_partner_name': 'العميل/المورد: {name}',
      'di_discount': 'الخصم: {amount} د.ك',
      'di_paid': 'المدفوع: {amount} د.ك',
      'di_remainder': 'المتبقي: {amount} د.ك',
      'di_cashier': 'الكاشير: {name}',
      'di_invoice_items': 'عناصر الفاتورة:',
      'di_item_details': '{name}  -  الكمية: {qty}  -  السعر: {price} د.ك  -  الإجمالي: {total} د.ك',
      'di_total_col': 'الإجمالي',
      'di_price_col': 'السعر',
      'di_qty_col': 'الكمية',
      'di_item_col': 'الصنف',
      'di_grand_total': 'الإجمالي الكلي',
      'di_net_total': 'الصافي الكلي',
      'di_register_payment': 'تسجيل سداد دفعة',
      'di_reprint': 'إعادة طباعة',
      'di_close_popup': 'إغلاق',
      'di_payment_dialog_title': 'تسجيل سداد للفاتورة الآجلة',
      'di_payment_remaining': 'المتبقي غير المدفوع: {amount} د.ك',
      'di_payment_amount_label': 'مبلغ السداد المستلم',
      'di_cancel': 'إلغاء',
      'di_confirm_payment': 'تأكيد السداد',
      'di_invalid_payment': 'الرجاء إدخال مبلغ صحيح لا يتجاوز المتبقي',
      'di_payment_success': 'تم تسجيل السداد بنجاح وتحديث القيود المحاسبية!',
      'di_payment_fail': 'فشل تسجيل السداد: {error}',
      'di_payment_error': 'خطأ أثناء عملية السداد: {error}',
      'di_fetch_fail': 'فشل جلب تفاصيل الفاتورة من الخادم',
      'di_network_error': 'خطأ أثناء الاتصال بالشبكة: {error}',
      'cs_summary_fetch_error': 'تعذر جلب ملخص الوردية. تأكد من وجود وردية مفتوحة.',
      'cs_data_load_error': 'خطأ في تحميل البيانات: {error}',
      'cs_enter_actual_cash': 'الرجاء إدخال النقدية الفعلية أولاً',
      'cs_offline_data_warning': 'الرجاء التأكد من وجود اتصال بالإنترنت وحفظ كافة الفواتير والسندات قبل إغلاق الوردية.',
      'cs_confirm_close_title': 'تأكيد إغلاق الوردية',
      'cs_confirm_close_msg': 'هل أنت متأكد من إغلاق الوردية الحالية؟\nلا يمكن التراجع عن هذه العملية.',
      'cs_cancel': 'إلغاء',
      'cs_close_shift': 'إغلاق الوردية',
      'cs_success': 'نجاح',
      'cs_close_success_msg': 'تم إغلاق الوردية بنجاح.',
      'cs_ok': 'موافق',
      'cs_error': 'خطأ',
      'cs_close_error_msg': 'حدث خطأ أثناء إغلاق الوردية: {error}',
      'cs_screen_title': 'إغلاق الوردية وتسليم النقدية',
      'cs_financial_summary': 'ملخص ماليات الوردية',
      'cs_starting_cash': 'العهدة الابتدائية',
      'cs_total_paid_sales': 'إجمالي مبيعات نقدية',
      'cs_total_paid_purchases': 'إجمالي مشتريات نقدية',
      'cs_total_receipts': 'إجمالي سندات قبض',
      'cs_total_payments': 'إجمالي سندات صرف',
      'cs_expected_cash': 'إجمالي النقدية المتوقعة',
      'cs_actual_cash': 'النقدية الفعلية (بالدرج)',
      'cs_enter_actual_cash_hint': 'أدخل النقدية الفعلية هنا',
      'cs_difference': 'العجز / الزيادة',
      'cs_close_print_btn': 'إغلاق وطباعة التقرير',
      'cs_unsynced_data_title': 'بيانات غير متزامنة',
      'cs_unsynced_data_msg': 'يوجد {invoices} فواتير و {vouchers} سندات غير متزامنة.\nيجب مزامنتها مع الخادم قبل إغلاق الوردية.',
      'cs_sync_now': 'مزامنة الآن',
      'cs_sync_failed': 'فشلت مزامنة بعض البيانات. يرجى التحقق من اتصالك بالإنترنت.',
      'cs_sync_success': 'تمت المزامنة بنجاح.',
      'cs_entered_cash': 'الكاش الختامي المُدخل: {amount} د.ك',
      'cs_expected_cash_msg': 'الكاش المتوقع: {amount} د.ك',
      'cs_difference_msg': 'الفرق: {amount} د.ك',
      'cs_confirm_close_with_print_msg': 'هل أنت متأكد من إغلاق الوردية؟\nسيتم طباعة تقرير اليومية قبل الإغلاق.',
      'cs_yes_close_shift': 'نعم، أغلق الوردية',
      'cs_printing': 'جاري الطباعة...',
      'cs_closed_successfully': 'تم الإغلاق بنجاح',
      'cs_closing': 'جاري الإغلاق...',
      'cs_printer_error': 'فشل في الاتصال بالطابعة',
      'cs_cashier': 'الكاشير',
      'cs_open_time': 'وقت الفتح',
      'cs_status': 'الحالة',
      'cs_sales_summary': '📈 مبيعات الوردية',
      'cs_invoice_count': '{count} فاتورة',
      'cs_total_sales_label': 'إجمالي المبيعات',
      'cs_paid_sales_label': 'مُسدَّد نقداً',
      'cs_credit_sales_label': 'آجل متبقي',
      'cs_purchases_summary': '📦 مشتريات الوردية',
      'cs_total_purchases_label': 'إجمالي المشتريات',
      'cs_paid_purchases_label': 'مُسدَّد نقداً',
      'cs_credit_purchases_label': 'آجل متبقي',
      'cs_cash_drawer_calc': '💰 تسوية الكاش',
      'cs_add_receipts': '+ سندات قبض',
      'cs_subtract_payments': '- سندات صرف',
      'cs_loading_summary': 'جاري تحميل ملخص الوردية...',
      'cs_retry': 'إعادة المحاولة',
      'cs_shift_info': '📋 معلومات الوردية',
      'cs_invoices_count': 'عدد الفواتير',
      'cs_vouchers_summary': '🧾 السندات المالية',
      'cs_add_paid_sales': '+ مبيعات مسددة',
      'cs_sub_paid_purchases': '- مشتريات مسددة',
      'cs_sub_payments': '- سندات صرف',
      // Close Shift Screen
      'cs_error_fetch_summary': 'تعذر جلب ملخص الوردية. تأكد من وجود وردية مفتوحة.',
      'cs_error_load_data': 'خطأ في تحميل البيانات: {error}',
      'cs_no_open_shift': 'لا توجد وردية مفتوحة',
      'cs_unsynced_data_title': 'بيانات غير متزامنة',
      'cs_unsynced_data_content': 'يوجد {invoices} فواتير و {vouchers} سندات غير متزامنة.\nيجب مزامنتها مع الخادم قبل إغلاق الوردية.',
      'cs_cancel': 'إلغاء',
      'cs_sync_now': 'مزامنة الآن',
      'cs_sync_failed': 'فشلت مزامنة بعض البيانات. يرجى التحقق من اتصالك بالإنترنت.',
      'cs_sync_success': 'تمت المزامنة بنجاح.',
      'cs_confirm_close_title': 'تأكيد إغلاق الوردية',
      'cs_ending_cash_entered': 'الكاش الختامي المُدخل: {amount} KWD',
      'cs_expected_cash': 'الكاش المتوقع: {amount} KWD',
      'cs_difference': 'الفرق: {amount} KWD',
      'cs_confirm_close_content': 'هل أنت متأكد من إغلاق الوردية؟\nسيتم طباعة تقرير اليومية قبل الإغلاق.',
      'cs_yes_close': 'نعم، أغلق الوردية',
      'cs_close_success': 'تم إغلاق الوردية بنجاح ✓',
      'cs_close_failed': 'فشل إغلاق الوردية: {error}',
      'cs_screen_title': 'إغلاق الوردية',
      'cs_loading_summary': 'جاري تحميل ملخص الوردية...',
      'cs_retry': 'إعادة المحاولة',
      'cs_shift_info_card': '📋 معلومات الوردية',
      'cs_cashier': 'الكاشير',
      'cs_open_time': 'وقت الفتح',
      'cs_status': 'الحالة',
      'cs_sales_card': '📈 مبيعات الوردية',
      'cs_invoices_count': 'عدد الفواتير',
      'cs_invoices_count_val': '{count} فاتورة',
      'cs_total_sales': 'إجمالي المبيعات',
      'cs_paid_cash': 'مُسدَّد نقداً',
      'cs_credit_remainder': 'آجل متبقي',
      'cs_purchases_card': '📦 مشتريات الوردية',
      'cs_total_purchases': 'إجمالي المشتريات',
      'cs_vouchers_card': '🧾 السندات المالية',
      'cs_total_receipt_vouchers': 'إجمالي سندات القبض',
      'cs_total_payment_vouchers': 'إجمالي سندات الصرف',
      'cs_cash_settlement_card': '💰 تسوية الكاش',
      'cs_starting_cash': 'عهدة الافتتاح',
      'cs_plus_paid_sales': '+ مبيعات مسددة',
      'cs_minus_paid_purchases': '- مشتريات مسددة',
      'cs_plus_receipt_vouchers': '+ سندات قبض',
      'cs_minus_payment_vouchers': '- سندات صرف',
      'cs_equals_expected_cash': '= الكاش المتوقع',
      'cs_enter_actual_cash': 'أدخل الكاش الختامي الفعلي:',
      'cs_printing': 'جاري الطباعة...',
      'cs_closing': 'جاري الإغلاق...',
      'cs_print_and_close': 'طباعة التقرير وإغلاق الوردية',
      // Printer Settings Screen
      'ps_save_success': 'تم حفظ إعدادات الطابعة بنجاح!',
      'ps_save_failed': 'فشل في حفظ الإعدادات',
      'ps_test_simulated': 'تمت محاكاة الطباعة التجريبية بنجاح في الكونسول (الطباعة الفعلية معطلة)',
      'ps_test_success': 'تمت الطباعة التجريبية بنجاح على الطابعة المحددة!',
      'ps_test_failed': 'فشل في طباعة الفاتورة التجريبية، يرجى التحقق من اتصال وإعدادات الطابعة',
      'ps_screen_title': 'إعدادات الطابعة الحرارية',
      'ps_config_title': 'تكوين طابعة إيصالات الكاشير (POS)',
      'ps_synced': 'مزامنة نشطة مع السيرفر',
      'ps_offline': 'حفظ محلي فقط (أوفلاين)',
      'ps_conn_type': 'نوع الاتصال الطابعة',
      'ps_conn_none': 'غير متصلة (تعطيل الطباعة)',
      'ps_conn_network': 'شبكي (Network IP Printer)',
      'ps_conn_bluetooth': 'بلوتوث (Bluetooth Printer)',
      'ps_ip_label': 'عنوان IP الطابعة (مثال: 192.168.1.100)',
      'ps_port_label': 'منفذ الاتصال (Port - افتراضي 9100)',
      'ps_bt_device': 'جهاز طابعة البلوتوث',
      'ps_bt_clear': 'إلغاء التحديد',
      'ps_bt_selected': 'الطابعة المحددة حالياً للتشغيل',
      'ps_bt_scan_searching': 'جاري البحث عن أجهزة...',
      'ps_bt_scan_button': 'البحث عن الطابعات المتوفرة (Scan)',
      'ps_bt_scan_desc': 'جاري فحص النطاق والبحث عن أجهزة بلوتوث نشطة...',
      'ps_bt_found': 'الطابعات التي تم العثور عليها:',
      'ps_test_print_btn': 'طباعة تجريبية',
      'ps_save_btn': 'حفظ الإعدادات',
    },
    'en': {
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'General Settings',
      'home': 'Home',
      // Login Screen
      'login_title': 'Login',
      'login_username_hint': 'Username',
      'login_password_hint': 'Password',
      'login_button': 'Enter',
      'login_empty_error': 'Please enter username and password',
      'login_failed_fallback': 'Login failed',
      // License Screen
      'license_whatsapp_error':
          'Could not open WhatsApp, please message 55381505 manually',
      'license_copied': 'Device HWID copied to clipboard successfully!',
      'license_title': 'Vegtablity POS Protection',
      'license_checking': 'Checking device license...',
      'license_expired_title': 'Subscription Expired!',
      'license_expired_desc':
          'Sorry, your subscription for this device expired on ',
      'license_expired_desc_2':
          '.\nPlease renew your subscription with technical support to continue.',
      'license_error_title': 'Connection Error!',
      'license_inactive_title': 'License Inactive!',
      'license_inactive_desc':
          'This device is registered but the license is temporarily suspended.\nPlease contact technical support for activation.',
      'license_unregistered_title': 'Unregistered Device!',
      'license_unregistered_desc':
          'The hardware ID of this device is not registered in our system.\nPlease send your device HWID to technical support for registration.',
      'license_hwid_label': 'Your Device HWID',
      'license_support_title': 'Technical Support & Licensing',
      'license_phone_label': 'Phone:',
      'license_send_whatsapp': 'Send HWID via WhatsApp',
      'license_info_button': 'More Info',
      'license_retry_button': 'Retry Check',
      // Shift Screen
      'shift_open_error_empty': 'Please enter a valid starting cash amount',
      'shift_open_failed_fallback': 'Failed to open shift',
      'shift_checking_status': 'Checking shift status...',
      'shift_wait_data': 'Please wait while loading data from the server',
      'shift_new_title': 'Open New Shift',
      'shift_confirm_cash': 'Confirm Cashier Starting Cash',
      'shift_cash_label': 'Amount (Cash)',
      'shift_open_button': 'Open Shift & Start Work',
      // Home Screen
      'home_title': 'Smart Cashier System (POS)',
      'home_server_status': 'Server Status: ',
      'home_welcome': 'Welcome: ',
      'home_developed_by': 'Developed by Mohamed Ragab',
      'home_printer_settings': 'Thermal Printer Settings',
      'home_daily_invoices': 'Daily Invoices Report',
      'home_close_shift': 'Close Shift',
      'home_receipt_voucher': 'Receipt Voucher',
      'home_receipt_voucher_sub': 'Collect Revenue (Direct)',
      'home_payment_voucher': 'Payment Voucher',
      'home_payment_voucher_sub': 'Pay Expenses (Direct)',
      'home_logout': 'Logout',
      'home_offline_invoices_1': 'You have ',
      'home_offline_invoices_2': ' offline invoice(s) waiting to be synced.',
      'home_sync_success': 'Sync Successful',
      'home_sync_failed': 'Sync Failed',
      'home_sync_now': 'Sync Now',
      'home_offline_vouchers_2': ' offline voucher(s) waiting to be synced.',
      'home_sync': 'Sync',
      'home_classic_new_invoice': 'New Sales Invoice',
      'home_classic_manage_partners': 'Manage Suppliers/Customers',
      'home_classic_sales_quote': 'Load Sales Quote',
      'home_premium_customer_sales': 'Customer Sales',
      'home_premium_supplier_purchases': 'Supplier Purchases',
      'home_premium_customer_receipts': 'Customer Receipts',
      'home_premium_receipts_sub': 'Receipt Vouchers',
      'home_premium_supplier_payments': 'Supplier Payments',
      'home_premium_payments_sub': 'Payment Vouchers',
      // Settings Screen
      'settings_save_success':
          'New layout saved and Home Screen updated successfully',
      'settings_save_error':
          'An error occurred while saving settings. Please try again later',
      'settings_layout_title': 'Home Screen Layout & Design',
      'settings_layout_desc':
          'Choose the interface you want to work with. The preference is loaded automatically on startup.',
      'settings_classic_title': 'Classic Layout (Default)',
      'settings_classic_desc':
          'The original interface that provides quick access to direct manual sales, supplier management, and public offers.',
      'settings_premium_title': 'Partners Offers Layout (New)',
      'settings_premium_desc':
          'A POS interface fully dedicated to active partner offers (purchases/sales), preventing products outside the offer and supporting cash or credit payments.',
      // POS Screen
      'pos_barcode_simulator_title': 'Barcode & Product Simulator',
      'pos_barcode_simulator_input': 'Enter barcode or product name',
      'pos_cancel': 'Cancel',
      'pos_add_to_cart': 'Add to Cart',
      'pos_sales_title': 'Point of Sale',
      'pos_purchases_title': 'Purchase Invoice',
      'pos_barcode_input': 'Enter barcode or product name manually',
      'pos_empty_cart':
          'Cart is empty. Scan or enter product barcodes to start.',
      'pos_item_price': 'Price: ',
      'pos_item_quantity': ' | Qty: ',
      'pos_save_success_warn':
          'Invoice ({id}) saved but printer connection failed',
      'pos_save_success_ok': 'Invoice ({id}) saved and printed successfully',
      'pos_print_status_printed': 'Printed',
      'pos_print_status_virtual': 'Virtual',
      'pos_print_status_failed': 'Print Failed',
      'pos_save_failed': 'Failed to save invoice',
      'pos_total': 'Total',
      'pos_pay_print': 'Pay & Print (F12)',
      // Partner Offers Screen
      'po_error_fetch_partners': 'Failed to retrieve active partners data',
      'po_error_network': 'Network error occurred: ',
      'po_loading_quote': 'Loading offer details and approved prices...',
      'po_no_active_quote':
          'No active or approved quote for this partner currently!',
      'po_error_loading_quote': 'Error loading quote: ',
      'po_sales_partners_title': 'Active Sales Offer Customers',
      'po_purchases_partners_title': 'Active Purchase Offer Suppliers',
      'po_search_hint': 'Search by partner name or phone...',
      'po_retry': 'Retry',
      'po_no_partners_found': 'No active partners match the search currently.',
      'po_no_phone': 'No Phone',
      'po_no_address': 'Address not specified',
      // Partner Billing Screen
      'pb_unknown_item': 'Unknown Item',
      'pb_item_piece': 'Pcs',
      'pb_item_added': 'Added: ',
      'pb_alert_unapproved': 'Alert - Unapproved Item',
      'pb_alert_unapproved_desc':
          'The barcode ({barcode}) is not listed in the active approved quote for this partner!\n\nAdding products outside the offer is prohibited.',
      'pb_ok': 'OK',
      'pb_scan_camera_title': 'Scan Barcode via Camera',
      'pb_scan_camera_hint': 'Point the camera at the item barcode',
      'pb_cart_empty_error': 'Cart is empty! Please add products first',
      'pb_offer_notes': 'Partner Offers Invoice - Quote No. ',
      'pb_save_success':
          'Invoice No. ({id}) added successfully and print command sent.',
      'pb_save_server_fail': 'Failed to save invoice on server: ',
      'pb_network_error': 'Network error: ',
      'pb_sales_offer_invoice': 'Sales Offer Invoice',
      'pb_purchase_offer_invoice': 'Purchase Offer Invoice',
      'pb_partner_name': 'Partner: ',
      'pb_scan_tooltip': 'Scan barcode with camera',
      'pb_items_in_cart': 'Items in Cart: ',
      'pb_total_kd': 'Total: {total} KWD',
      'pb_search_hint': 'Search by product name or barcode...',
      'pb_barcode_hint': 'Enter barcode...',
      'pb_approved_items_title': 'Approved Items and Prices in Partner Offer:',
      'pb_no_barcode': 'No Barcode',
      'pb_cart_title': 'Shopping Cart / Current Invoice',
      'pb_cart_empty': 'Cart is empty\nTap on items to add them',
      'pb_item_price': 'Price: ',
      'pb_item_quantity': ' KWD | Qty: ',
      'pb_subtotal': 'Subtotal:',
      'pb_discount_value': 'Discount:',
      'pb_net_amount': 'Net Amount:',
      'pb_pay_cash': 'Pay Cash (F12)',
      'pb_pay_credit': 'Pay Credit',
      'pb_no_results': 'No matching results found',
      'pb_add_btn': 'Add',
      'pb_view_cart': 'View Cart ({count})',
      'pb_current_cart': 'Current Cart Contents:',
      'pb_empty_cart_short': 'Cart is empty',
      'pb_final_net': 'Final Net Total: {total} KWD',
      // Payment Voucher Screen
      'pv_offline_error': 'You are offline. You can enter a free payment.',
      'pv_supplier_required': 'Please select a supplier first',
      'pv_invoice_or_free_required':
          'Please select at least one invoice or enter a free payment amount',
      'pv_account_required': 'Please select a payment account',
      'pv_no_shift_open': 'No open shift found',
      'pv_confirm_title': 'Confirm Payment Voucher',
      'pv_confirm_desc':
          'A payment voucher will be recorded with the amount of\n{amount} KWD\nfor Supplier: {partner}',
      'pv_cancel': 'Cancel',
      'pv_confirm': 'Confirm',
      'pv_default_desc': 'Payment Voucher - ',
      'pv_save_print_success':
          'Voucher No. ({id}) saved and printed successfully',
      'pv_save_error': 'Unexpected error: ',
      'pv_screen_title': 'Payment Voucher',
      'pv_supplier_label': 'Supplier: ',
      'pv_search_hint': 'Search supplier by name or phone...',
      'pv_no_suppliers': 'No suppliers found',
      'pv_no_dues': 'No dues for this supplier',
      'pv_account_label': 'Payment Account',
      'pv_note_hint': 'Note (optional)...',
      'pv_no_invoices':
          'No invoices (or offline).\nYou can enter a free payment (account payment).',
      'pv_free_payment_label': 'Free Payment Amount (Account Payment)',
      'pv_purchase_invoice_label': 'Purchase Invoice #',
      'pv_total_label': 'Total: ',
      'pv_remainder_label': 'Remainder: {amount} KWD',
      'pv_payment_amount_label': 'Payment Amount: ',
      'pv_selected_invoices': '{count} Selected Invoices',
      'pv_submit_button': 'Record Payment',
      // Receipt Voucher Screen
      'rv_offline_error': 'You are offline. Cannot fetch invoices. Please enter a free payment amount.',
      'rv_customer_required': 'Please select a customer first',
      'rv_invoice_or_free_required': 'Please select at least one invoice or enter a free payment amount',
      'rv_account_required': 'Please select a receipt account',
      'rv_no_shift_open': 'No open shift found',
      'rv_confirm_title': 'Confirm Receipt Voucher',
      'rv_confirm_desc': 'A receipt voucher will be recorded with the amount of\n{amount} KWD\nfrom Customer: {partner}',
      'rv_cancel': 'Cancel',
      'rv_confirm': 'Confirm',
      'rv_default_desc': 'Receipt Voucher - ',
      'rv_save_print_success': 'Voucher No. ({id}) saved and printed successfully',
      'rv_save_error': 'Unexpected error: ',
      'rv_screen_title': 'Receipt Voucher',
      'rv_customer_label': 'Customer: ',
      'rv_search_hint': 'Search customer by name or phone...',
      'rv_no_customers': 'No customers found',
      'rv_no_dues': 'No dues for this customer',
      'rv_account_label': 'Receipt Account',
      'rv_note_hint': 'Note (optional)...',
      'rv_no_invoices': 'Cannot fetch invoices (or none exist).\nYou can enter a free payment (account payment).',
      'rv_free_payment_label': 'Free Payment Amount (Account Payment)',
      'rv_sales_invoice_label': 'Invoice #',
      'rv_total_label': 'Total: ',
      'rv_remainder_label': 'Remainder: {amount} KWD',
      'rv_receipt_amount_label': 'Receipt Amount: ',
      'rv_selected_invoices': '{count} Selected Invoices',
      'rv_submit_button': 'Record Receipt',
      // General Payment Voucher Screen
      'gpv_choose_expense_account': 'Choose Expense Account',
      'gpv_search_account_hint': 'Search for an account...',
      'gpv_account_code': 'Code: {code}',
      'gpv_expense_account_required': 'Please select the target account (Expenses)',
      'gpv_amount_required': 'Please enter the amount',
      'gpv_invalid_amount': 'Invalid amount',
      'gpv_cash_account_required': 'Please select the cash/bank account',
      'gpv_undefined': 'Undefined',
      'gpv_cash': 'Cash',
      'gpv_save_print_success': 'Payment voucher created and printed successfully (No. {id})',
      'gpv_save_error': 'Error during saving: ',
      'gpv_cannot_save': 'Cannot save: ',
      'gpv_screen_title': 'Direct Payment Voucher (Expenses)',
      'gpv_target_account_label': 'Target Account (Expense)',
      'gpv_click_to_choose': 'Tap to choose account',
      'gpv_amount_label': 'Amount (KWD)',
      'gpv_statement_label': 'Statement / Notes',
      'gpv_pay_from_account': 'Pay from account (Cashier)',
      'gpv_save_button': 'Save Direct Voucher',
      // General Receipt Voucher Screen
      'grv_choose_revenue_account': 'Choose Revenue Account',
      'grv_revenue_account_required': 'Please select the target account (Revenues)',
      'grv_save_print_success': 'Receipt voucher created and printed successfully (No. {id})',
      'grv_screen_title': 'Direct Receipt Voucher (Revenues)',
      'grv_target_account_label': 'Target Account (Revenue)',
      'grv_receive_to_account': 'Receive to Account (Cash)',
      'grv_save_button': 'Save Direct Voucher',
      // Daily Invoices Screen
      'di_fetch_error': 'Failed to retrieve today\'s invoices from server',
      'di_error_loading': 'Error loading invoices: {error}',
      'di_screen_title': 'Daily Invoices & User Report',
      'di_total_sales': 'Total Sales',
      'di_total_purchases': 'Total Purchases',
      'di_net_income': 'Net Income (Sales - Purchases)',
      'di_total_receipts': 'Receipt Vouchers (In)',
      'di_total_payments': 'Payment Vouchers (Out)',
      'di_net_cash': 'Net Cash (Drawer)',
      'di_tab_sales': 'Sales',
      'di_tab_purchases': 'Purchases',
      'di_tab_receipts': 'Receipts',
      'di_tab_payments': 'Payments',
      'di_sales_invoices': 'Daily Customer Sales',
      'di_purchase_invoices': 'Daily Supplier Purchases',
      'di_receipt_vouchers': 'Receipt Vouchers (Collections)',
      'di_payment_vouchers': 'Payment Vouchers (Expenses)',
      'di_daily_financial_split': 'Daily Financial Split',
      'di_shift_financial_vouchers': 'Shift Financial Vouchers',
      'di_no_invoices': 'No data available',
      'di_invoice_no': 'Invoice No: #{id}',
      'di_date': 'Date: {date}',
      'di_time': 'Time: {time}',
      'di_net_amount': 'Net: {amount} KWD',
      'di_voucher_no': 'Voucher No: #{id}',
      'di_voucher_amount': 'Amount: {amount} KWD',
      'di_voucher_desc': 'Statement: {desc}',
      'di_print_button': 'Print Details',
      'di_print_success': 'Invoice printed successfully',
      'di_print_error': 'Failed to print invoice',
      'di_invoice_details': 'Invoice Details',
      'di_partner_name': 'Customer/Supplier: {name}',
      'di_discount': 'Discount: {amount} KWD',
'di_paid': 'Paid: {amount} KWD',
      'di_remainder': 'Remainder: {amount} KWD',
      'di_cashier': 'Cashier: {name}',
      'di_invoice_items': 'Invoice Items:',
      'di_item_details': '{name}  -  Qty: {qty}  -  Price: {price} KWD  -  Total: {total} KWD',
      'di_total_col': 'Total',
      'di_price_col': 'Price',
      'di_qty_col': 'Qty',
      'di_item_col': 'Item',
      'di_grand_total': 'Grand Total',
      'di_net_total': 'Net Total',
      'di_register_payment': 'Record Payment',
      'di_reprint': 'Reprint',
      'di_close_popup': 'Close',
      'di_payment_dialog_title': 'Record Credit Invoice Payment',
      'di_payment_remaining': 'Remaining Unpaid: {amount} KWD',
      'di_payment_amount_label': 'Payment Amount Received',
      'di_cancel': 'Cancel',
      'di_confirm_payment': 'Confirm Payment',
      'di_invalid_payment': 'Please enter a valid amount not exceeding the remainder',
      'di_payment_success': 'Payment recorded and accounting entries updated!',
      'di_payment_fail': 'Failed to record payment: {error}',
      'di_payment_error': 'Error during payment: {error}',
      'di_fetch_fail': 'Failed to fetch invoice details from server',
      'di_network_error': 'Network error: {error}',
      // Close Shift Screen
      'cs_summary_fetch_error': 'Failed to fetch shift summary. Make sure a shift is open.',
      'cs_data_load_error': 'Error loading data: {error}',
      'cs_enter_actual_cash': 'Please enter actual cash first',
      'cs_offline_data_warning': 'Please ensure internet connection and save all offline data before closing the shift.',
      'cs_confirm_close_title': 'Confirm Close Shift',
      'cs_confirm_close_msg': 'Are you sure you want to close the current shift?\nThis action cannot be undone.',
      'cs_cancel': 'Cancel',
      'cs_close_shift': 'Close Shift',
      'cs_success': 'Success',
      'cs_close_success_msg': 'Shift closed successfully.',
      'cs_ok': 'OK',
      'cs_error': 'Error',
      'cs_close_error_msg': 'Error closing shift: {error}',
      'cs_screen_title': 'Close Shift & Handover Cash',
      'cs_financial_summary': 'Shift Financial Summary',
      'cs_starting_cash': 'Starting Cash',
      'cs_total_paid_sales': 'Total Paid Sales',
      'cs_total_paid_purchases': 'Total Paid Purchases',
      'cs_total_receipts': 'Total Receipt Vouchers',
      'cs_total_payments': 'Total Payment Vouchers',
      'cs_expected_cash': 'Expected Total Cash',
      'cs_actual_cash': 'Actual Cash (in drawer)',
      'cs_enter_actual_cash_hint': 'Enter actual cash here',
      'cs_difference': 'Deficit / Surplus',
      'cs_close_print_btn': 'Close & Print Report',
      'cs_unsynced_data_title': 'Unsynced Data',
      'cs_unsynced_data_msg': 'There are {invoices} invoices and {vouchers} vouchers unsynced.\nThey must be synced before closing the shift.',
      'cs_sync_now': 'Sync Now',
      'cs_sync_failed': 'Failed to sync some data. Please check your internet connection.',
      'cs_sync_success': 'Synced successfully.',
      'cs_entered_cash': 'Entered Closing Cash: {amount} KWD',
      'cs_expected_cash_msg': 'Expected Cash: {amount} KWD',
      'cs_difference_msg': 'Difference: {amount} KWD',
      'cs_confirm_close_with_print_msg': 'Are you sure you want to close the shift?\nA daily report will be printed before closing.',
      'cs_yes_close_shift': 'Yes, Close Shift',
      'cs_printing': 'Printing...',
      'cs_closed_successfully': 'Closed successfully',
      'cs_closing': 'Closing...',
      'cs_printer_error': 'Failed to connect to printer',
      'cs_cashier': 'Cashier',
      'cs_open_time': 'Open Time',
      'cs_status': 'Status',
      'cs_sales_summary': '📈 Shift Sales',
      'cs_invoice_count': '{count} Invoices',
      'cs_total_sales_label': 'Total Sales',
      'cs_paid_sales_label': 'Paid in Cash',
      'cs_credit_sales_label': 'Remaining Credit',
      'cs_purchases_summary': '📦 Shift Purchases',
      'cs_total_purchases_label': 'Total Purchases',
      'cs_paid_purchases_label': 'Paid in Cash',
      'cs_credit_purchases_label': 'Remaining Credit',
      'cs_cash_drawer_calc': '💰 Cash Settlement',
      'cs_add_receipts': '+ Receipt Vouchers',
      'cs_subtract_payments': '- Payment Vouchers',
      'cs_loading_summary': 'Loading shift summary...',
      'cs_retry': 'Retry',
      'cs_shift_info': '📋 Shift Information',
      'cs_invoices_count': 'Invoices Count',
      'cs_vouchers_summary': '🧾 Financial Vouchers',
      'cs_add_paid_sales': '+ Paid Sales',
      'cs_sub_paid_purchases': '- Paid Purchases',
      'cs_sub_payments': '- Payment Vouchers',
      // Close Shift Screen
      'cs_error_fetch_summary': 'Failed to fetch shift summary. Ensure a shift is open.',
      'cs_error_load_data': 'Error loading data: {error}',
      'cs_no_open_shift': 'No open shift',
      'cs_unsynced_data_title': 'Unsynced Data',
      'cs_unsynced_data_content': 'There are {invoices} invoices and {vouchers} vouchers not synced.\nYou must sync them before closing the shift.',
      'cs_cancel': 'Cancel',
      'cs_sync_now': 'Sync Now',
      'cs_sync_failed': 'Some data failed to sync. Check your internet connection.',
      'cs_sync_success': 'Synced successfully.',
      'cs_confirm_close_title': 'Confirm Shift Close',
      'cs_ending_cash_entered': 'Entered Ending Cash: {amount} KWD',
      'cs_expected_cash': 'Expected Cash: {amount} KWD',
      'cs_difference': 'Difference: {amount} KWD',
      'cs_confirm_close_content': 'Are you sure you want to close the shift?\nThe daily report will be printed before closing.',
      'cs_yes_close': 'Yes, Close Shift',
      'cs_close_success': 'Shift closed successfully ✓',
      'cs_close_failed': 'Failed to close shift: {error}',
      'cs_screen_title': 'Close Shift',
      'cs_loading_summary': 'Loading shift summary...',
      'cs_retry': 'Retry',
      'cs_shift_info_card': '📋 Shift Info',
      'cs_cashier': 'Cashier',
      'cs_open_time': 'Open Time',
      'cs_status': 'Status',
      'cs_sales_card': '📈 Shift Sales',
      'cs_invoices_count': 'Invoices Count',
      'cs_invoices_count_val': '{count} invoice(s)',
      'cs_total_sales': 'Total Sales',
      'cs_paid_cash': 'Paid in Cash',
      'cs_credit_remainder': 'Credit Remainder',
      'cs_purchases_card': '📦 Shift Purchases',
      'cs_total_purchases': 'Total Purchases',
      'cs_vouchers_card': '🧾 Vouchers',
      'cs_total_receipt_vouchers': 'Total Receipt Vouchers',
      'cs_total_payment_vouchers': 'Total Payment Vouchers',
      'cs_cash_settlement_card': '💰 Cash Settlement',
      'cs_starting_cash': 'Starting Cash',
      'cs_plus_paid_sales': '+ Paid Sales',
      'cs_minus_paid_purchases': '- Paid Purchases',
      'cs_plus_receipt_vouchers': '+ Receipt Vouchers',
      'cs_minus_payment_vouchers': '- Payment Vouchers',
      'cs_equals_expected_cash': '= Expected Cash',
      'cs_enter_actual_cash': 'Enter actual ending cash:',
      'cs_printing': 'Printing...',
      'cs_closing': 'Closing...',
      'cs_print_and_close': 'Print Report & Close Shift',
      // Printer Settings Screen
      'ps_save_success': 'Printer settings saved successfully!',
      'ps_save_failed': 'Failed to save settings',
      'ps_test_simulated': 'Test print simulated in console successfully (Actual printing disabled)',
      'ps_test_success': 'Test printed successfully on the selected printer!',
      'ps_test_failed': 'Failed to print test invoice, please check printer connection and settings',
      'ps_screen_title': 'Thermal Printer Settings',
      'ps_config_title': 'Cashier POS Printer Configuration',
      'ps_synced': 'Active sync with server',
      'ps_offline': 'Local save only (Offline)',
      'ps_conn_type': 'Printer Connection Type',
      'ps_conn_none': 'None (Disable printing)',
      'ps_conn_network': 'Network (Network IP Printer)',
      'ps_conn_bluetooth': 'Bluetooth (Bluetooth Printer)',
      'ps_ip_label': 'Printer IP Address (e.g., 192.168.1.100)',
      'ps_port_label': 'Connection Port (Default 9100)',
      'ps_bt_device': 'Bluetooth Printer Device',
      'ps_bt_clear': 'Clear Selection',
      'ps_bt_selected': 'Currently selected printer for operation',
      'ps_bt_scan_searching': 'Searching for devices...',
      'ps_bt_scan_button': 'Search for available printers (Scan)',
      'ps_bt_scan_desc': 'Scanning range for active bluetooth devices...',
      'ps_bt_found': 'Printers found:',
      'ps_test_print_btn': 'Test Print',
      'ps_save_btn': 'Save Settings',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// Extension for easier translation
extension TranslateExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
