import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'الإعدادات العامة',
      'home': 'الرئيسية',
      // Login Screen
      'login_title': 'تسجيل الدخول',
      'login_username_hint': 'اسم المستخدم',
      'login_password_hint': 'كلمة المرور',
      'login_button': 'دخول',
      'login_empty_error': 'يرجى إدخال اسم المستخدم وكلمة المرور',
      'login_failed_fallback': 'فشل تسجيل الدخول',
      // License Screen
      'license_whatsapp_error':
          'تعذر فتح تطبيق WhatsApp، يرجى مراسلة الرقم 55381505 يدوياً',
      'license_copied': 'تم نسخ بصمة الجهاز إلى الحافظة بنجاح!',
      'license_title': 'حماية Vegtablity POS',
      'license_checking': 'جاري التحقق من ترخيص هذا الجهاز...',
      'license_expired_title': 'انتهت صلاحية الاشتراك!',
      'license_expired_desc':
          'نأسف، لقد انتهت صلاحية اشتراك هذا الجهاز بتاريخ ',
      'license_expired_desc_2':
          '.\nيرجى تجديد الاشتراك مع الدعم الفني للاستمرار في العمل.',
      'license_error_title': 'خطأ في الاتصال!',
      'license_inactive_title': 'الترخيص غير نشط!',
      'license_inactive_desc':
          'هذا الجهاز مسجل لدينا ولكن تم إيقاف الترخيص مؤقتاً.\nيرجى مراجعة الدعم الفني لتفعيل صلاحية الدخول.',
      'license_unregistered_title': 'الجهاز غير مسجل!',
      'license_unregistered_desc':
          'رقم هوية هذا الجهاز غير مسجل في نظام التراخيص الخاص بنا.\nيرجى إرسال بصمة الجهاز للدعم الفني لتسجيله وتفعيله.',
      'license_hwid_label': 'بصمة الجهاز الخاصة بك',
      'license_support_title': 'الدعم الفني والترخيص',
      'license_phone_label': 'هاتف:',
      'license_send_whatsapp': 'إرسال البصمة عبر WhatsApp',
      'license_info_button': 'بيانات توضيحية',
      'license_retry_button': 'إعادة التحقق',
      // Shift Screen
      'shift_open_error_empty': 'يرجى إدخال مبلغ عهدة افتتاحية صحيح',
      'shift_open_failed_fallback': 'فشل فتح الوردية',
      'shift_checking_status': 'جاري التحقق من حالة الوردية...',
      'shift_wait_data': 'يرجى الانتظار لحين تحميل البيانات من السيرفر',
      'shift_new_title': 'فتح وردية جديدة',
      'shift_confirm_cash': 'تأكيد العهدة الافتتاحية للكاشير',
      'shift_cash_label': 'الرقم (الكاش)',
      'shift_open_button': 'فتح الوردية وبدء العمل',
      'shift_select_warehouse': 'اختر المستودع للوردية',
      'shift_warehouse_label': 'المستودع',
      'shift_warehouse_error': 'يرجى اختيار المستودع قبل فتح الوردية',
      // Home Screen
      'home_title': 'نظام الكاشير الذكي (POS)',
      'home_server_status': 'حالة السيرفر: ',
      'home_welcome': 'مرحباً: ',
      'home_active_shift': 'الوردية رقم: #',
      'home_no_active_shift': 'لا توجد وردية مفتوحة',
      'home_developed_by': 'Developed by Mohamed Ragab',
      'home_printer_settings': 'إعدادات الطابعة الحرارية',
      'home_open_cash_drawer': '💰 فتح درج النقدية',
      'cd_open_success': 'تم فتح درج النقدية بنجاح',
      'cd_open_failed':
          'عذراً، تعذر فتح درج النقدية في وضع البلوتوث أو التوصيل الحالي',
      'home_daily_invoices': 'تقرير الفواتير اليومية',
      'home_close_shift': 'إغلاق الوردية',
      'home_receipt_voucher': 'سند قبض',
      'home_receipt_voucher_sub': 'تحصيل إيرادات (مباشر)',
      'home_payment_voucher': 'سند صرف',
      'home_payment_voucher_sub': 'سداد مصروفات (مباشر)',
      'home_drawer_stocktake': 'جرد المخزون (مسودة)',
      'home_drawer_wastage': 'إهلاك بضاعة (الهالك)',
      'home_drawer_recipes': 'وصفات المنتجات والتصنيع',
      'home_logout': 'تسجيل الخروج',
      'home_offline_invoices_1': 'لديك ',
      'home_offline_invoices_2':
          ' فاتورة/فواتير محفوظة محلياً بانتظار المزامنة.',
      'home_sync_success': 'تمت المزامنة',
      'home_sync_failed': 'فشلت المزامنة',
      'home_sync_now': 'مزامنة الآن',
      'home_offline_vouchers_2': ' سند/سندات محفوظة محلياً بانتظار المزامنة.',
      'home_sync': 'مزامنة',
      'home_classic_new_invoice': 'فاتورة مبيعات جديدة',
      'home_classic_new_purchase': 'فاتورة مشتريات جديدة',
      'home_classic_stocktake': 'جرد المخزون',
      'home_classic_wastage': 'إهلاك بضاعة',
      'home_classic_manage_partners': 'إدارة الموردين/العملاء',
      'home_classic_sales_quote': 'استدعاء عرض مبيعات',
      'home_premium_customer_sales': 'مبيعات العملاء',
      'home_premium_supplier_purchases': 'مشتريات الموردين',
      'home_premium_customer_receipts': 'تحصيل العملاء',
      'home_premium_receipts_sub': 'سندات قبض',
      'home_premium_supplier_payments': 'دفع الموردين',
      'home_premium_payments_sub': 'سندات صرف',
      'home_daily_orders': 'الطلبات اليومية للتوصيل',
      'settings_show_daily_orders': 'إظهار بطاقة الطلبات اليومية للتوصيل',
      'home_recipes': 'وصفات المنتجات والتصنيع',
      'home_classic_recipes': 'وصفات المنتجات',
      'home_barcode_print': 'طباعة ملصقات الباركود',
      'settings_show_barcode_print': 'إظهار خيار طباعة الباركود في السايد بار',
      'barcode_print_title': 'طباعة ملصقات الباركود',
      'barcode_search_hint': 'ابحث باسم الصنف أو رقم الباركود...',
      'barcode_copies_title': 'عدد نسخ الطباعة',
      'barcode_print_button': 'طباعة ملصقات الباركود 🖨️',
      'barcode_type_regular': 'صنف عادي',
      'barcode_type_manufactured': 'منتج مصنع',
      'barcode_type_intermediate': 'منتج وسيط',
      'barcode_print_success': 'تمت طباعة ملصق الباركود بنجاح',
      'barcode_print_failed': 'فشلت عملية طباعة الباركود',
      'barcode_select_product_prompt': 'انقر على أي منتج لاختياره وتحديد عدد النسخ للطباعة',
      'barcode_preview_title': 'معاينة ملصق الباركود',
      'barcode_category_all': 'الكل',
      // Settings Screen
      'settings_home_modules_title': 'تخصيص معروضات الصفحة الرئيسية',
      'settings_home_modules_desc':
          'اختر الاختصارات والبطاقات التي تود ظهورها في الصفحة الرئيسية:',
      'home_no_enabled_cards_warn':
          'يرجى تفعيل بطاقة واحدة على الأقل من الإعدادات العامة لعرضها هنا',
      'settings_save_success':
          'تم حفظ النمط الجديد وتحديث واجهة الشاشة الرئيسية بنجاح',
      'settings_save_error': 'حدث خطأ أثناء حفظ الإعدادات يرجى المحاولة لاحقاً',
      'settings_layout_title': 'مظهر وتصميم الشاشة الرئيسية',
      'settings_layout_desc':
          'اختر الواجهة التي ترغب بالعمل عليها. يتم تحميل التفضيل تلقائياً عند بدء التشغيل.',
      'settings_classic_title': 'النمط الكلاسيكي (الافتراضي)',
      'settings_classic_desc':
          'الواجهة الأصلية التي تتيح الوصول السريع لعمليات البيع اليدوية المباشرة وإدارة الموردين واستدعاء العروض العامة.',
      'settings_premium_title': 'نمط عروض الشركاء (الجديد)',
      'settings_premium_desc':
          'واجهة POS مخصصة بالكامل لعروض أسعار الشركاء النشطة (مشتريات/مبيعات)، تمنع إدخال منتجات خارج العرض وتدعم الدفع كاش أو آجل.',
      'settings_allow_edit_unposted_invoices': 'تفعيل تعديل الفواتير غير المرحلة (هذا الجهاز)',
      'settings_allow_edit_unposted_invoices_desc':
          'السماح بإعادة فتح وتعديل فواتير المبيعات والمشتريات غير المرحلة من شاشات البحث والتقارير اليومية',
      'inv_lookup_edit_btn': 'تعديل الفاتورة ✏️',
      'inv_lookup_posted_no_edit': 'الفاتورة مرحلة ولا يمكن تعديلها',
      'pos_edit_mode_title': 'وضع تعديل الفاتورة',
      'pos_editing_invoice_sales': 'جاري تعديل فاتورة مبيعات رقم #{id}',
      'pos_editing_invoice_purchase': 'جاري تعديل فاتورة مشتريات رقم #{id}',
      'pos_save_changes_btn': 'حفظ التعديلات',
      'pos_edit_success': 'تم تعديل وحفظ الفاتورة بنجاح!',
      'di_edit_invoice_btn': 'تعديل الفاتورة ✏️',
      // POS Screen
      'pos_barcode_simulator_title': 'محاكي قارئ الباركود والمنتجات',
      'pos_barcode_simulator_input': 'أدخل الباركود أو اسم المنتج',
      'pos_cancel': 'إلغاء',
      'pos_add_to_cart': 'إضافة للسلة',
      'pos_sales_title': 'نقطة بيع',
      'pos_purchases_title': 'فاتورة مشتريات',
      'pos_barcode_input': 'إدخال الباركود أو اسم المنتج يدوياً',
      'pos_empty_cart':
          'السلة فارغة. قم بمسح أو إدخال باركود المنتجات بدءاً بالعمل.',
      'pos_item_price': 'السعر: ',
      'pos_item_quantity': ' | الكمية: ',
      'pos_item_discount': 'خصم الصنف',
      'pos_gross_total': 'الإجمالي',
      'pos_total_discount': 'الخصم',
      'pos_net_total': 'الصافي',
      'pos_save_success_warn':
          'تم إضافة الفاتورة رقم ({id}) ولكن فشل الاتصال بالطابعة',
      'pos_save_success_ok': 'تمت الإضافة والطباعة للفاتورة رقم ({id})',
      'pos_print_status_printed': 'طُبعت',
      'pos_print_status_virtual': 'افتراضية',
      'pos_print_status_failed': 'فشل الطباعة',
      'pos_save_failed': 'فشل في حفظ الفاتورة',
      'pos_total': 'الإجمالي',
      'pos_pay_print': 'دفع وطباعة (F12)',
      'pos_split_payment': 'تقسيم وسائل الدفع',
      'pos_sales_title_with_partner': 'فاتورة مبيعات - {name}',
      'pos_purchase_title_with_partner': 'فاتورة مشتريات - {name}',
      'pos_purchase_title': 'فاتورة مشتريات جديدة',
      'pos_catalog_tooltip': 'عرض كتالوج المنتجات',
      'pos_customer': 'العميل',
      'pos_supplier': 'المورد',
      'pos_cash_general': 'نقدي (عام)',
      'pos_change_customer': 'تغيير العميل',
      'pos_change_supplier': 'تغيير المورد',
      'pos_unrecognized_title': 'صنف جديد غير معرف',
      'pos_barcode_label': 'رمز الباركود: {barcode}',
      'pos_sale_price': 'سعر البيع',
      'pos_save_and_add': 'حفظ وإضافة',
      'pos_invalid_price_error': 'الرجاء إدخال سعر صحيح أكبر من الصفر',
      'pos_quick_add_success': 'تم تسجيل الصنف وإضافته بنجاح',
      'pos_quick_add_error': 'حدث خطأ في التسجيل',
      'pos_catalog_title': 'كتالوج المنتجات',
      'pos_catalog_refresh': 'تحديث المنتجات',
      'pos_catalog_no_products': 'لا توجد منتجات نشطة حالياً',
      'pos_catalog_all': 'الكل',
      'pos_added_to_cart': 'تمت إضافة {name} لسلة المشتريات',
      'pos_trans_type': 'نوع المعاملة',
      'pos_credit_mode': 'آجل / ذمم',
      'pos_cash_mode': 'نقدي / كاش',
      'pos_payment_account': 'طريقة الدفع / الحساب',
      'pos_save_and_print': 'حفظ الفاتورة والطباعة',
      'pos_total_due': 'الإجمالي المستحق',
      'pos_finish_order': 'إنهاء الطلب',
      // Partner Offers Screen
      'po_error_fetch_partners': 'فشل استرجاع بيانات الشركاء النشطين',
      'po_error_network': 'حدث خطأ في الاتصال بالشبكة: ',
      'po_loading_quote': 'جاري تحميل تفاصيل العرض والأسعار المعتمدة...',
      'po_no_active_quote':
          'لا يوجد عرض أسعار نشط أو معتمد لهذا الشريك حالياً!',
      'po_error_loading_quote': 'حدث خطأ أثناء تحميل العرض: ',
      'po_sales_partners_title': 'عملاء عروض المبيعات النشطة',
      'po_purchases_partners_title': 'موردي عروض المشتريات النشطة',
      'po_search_hint': 'ابحث باسم الشريك أو رقم الهاتف...',
      'po_retry': 'إعادة المحاولة',
      'po_no_partners_found': 'لا يوجد شركاء نشطين متطابقين للبحث حالياً.',
      'po_no_phone': 'لا يوجد هاتف',
      'po_no_address': 'العنوان غير محدد',
      // Partner Billing Screen
      'pb_unknown_item': 'صنف غير معروف',
      'pb_item_piece': 'حبة',
      'pb_item_added': 'تم إضافة: ',
      'pb_alert_unapproved': 'تنبيه - صنف غير معتمد',
      'pb_alert_unapproved_desc':
          'الباركود ({barcode}) غير مدرج في عرض الأسعار النشط والعتمد لهذا الشريك!\n\nيُمنع إضافة منتجات من خارج العرض.',
      'pb_ok': 'موافق',
      'pb_scan_camera_title': 'مسح الباركود بالكاميرا',
      'pb_scan_camera_hint': 'وجه الكاميرا نحو باركود الصنف',
      'pb_cart_empty_error': 'السلة فارغة! يرجى إضافة منتجات أولاً',
      'pb_offer_notes': 'فاتورة عروض شركاء - عرض رقم ',
      'pb_save_success':
          'تم إضافة الفاتورة رقم ({id}) بنجاح وإرسال أمر الطباعة.',
      'pb_save_server_fail': 'فشل حفظ الفاتورة على السيرفر: ',
      'pb_network_error': 'خطأ في الاتصال بالشبكة: ',
      'pb_sales_offer_invoice': 'فاتورة مبيعات عروض',
      'pb_purchase_offer_invoice': 'فاتورة مشتريات عروض',
      'pb_partner_name': 'الشريك: ',
      'pb_scan_tooltip': 'مسح باركود بالكاميرا',
      'pb_items_in_cart': 'الأصناف في السلة: ',
      'pb_total_kd': 'الإجمالي: {total}',
      'pb_search_hint': 'ابحث باسم المنتج أو الباركود...',
      'pb_barcode_hint': 'أدخل الباركود...',
      'pb_approved_items_title': 'الأصناف والأسعار المعتمدة داخل عرض الشريك:',
      'pb_no_barcode': 'بلا باركود',
      'pb_cart_title': 'سلة المشتريات / الفاتورة الحالية',
      'pb_cart_empty': 'السلة فارغة\nانقر على الأصناف لإضافتها',
      'pb_item_price': 'السعر: ',
      'pb_item_quantity': ' | الكمية: ',
      'pb_subtotal': 'الإجمالي الفرعي:',
      'pb_discount_value': 'قيمة الخصم:',
      'pb_net_amount': 'الصافي النهائي:',
      'pb_pay_cash': 'حفظ كاش (F12)',
      'pb_pay_credit': 'حفظ آجل (Credit)',
      'pb_no_results': 'لا توجد نتائج مطابقة للبحث',
      'pb_add_btn': 'إضافة',
      'pb_view_cart': 'عرض السلة ({count})',
      'pb_current_cart': 'محتويات السلة الحالية:',
      'pb_empty_cart_short': 'السلة فارغة',
      'pb_final_net': 'الإجمالي النهائي الصافي: {total}',
      // Payment Voucher Screen
      'pv_offline_error': 'أنت في وضع عدم الاتصال. يمكن إدخال سداد حر.',
      'pv_supplier_required': 'يرجى اختيار مورد أولاً',
      'pv_invoice_or_free_required':
          'يرجى اختيار فاتورة واحدة على الأقل أو إدخال مبلغ سداد حر',
      'pv_account_required': 'يرجى اختيار حساب الصرف',
      'pv_no_shift_open': 'لا توجد وردية مفتوحة',
      'pv_confirm_title': 'تأكيد سند الصرف',
      'pv_confirm_desc':
          'سيتم تسجيل سند صرف بقيمة\n{amount}\nللمورد: {partner}',
      'pv_cancel': 'إلغاء',
      'pv_confirm': 'تأكيد',
      'pv_default_desc': 'سند صرف - ',
      'pv_save_print_success': 'تم الحفظ والطباعة للسند رقم ({id})',
      'pv_save_error': 'خطأ غير متوقع: ',
      'pv_screen_title': 'سند صرف',
      'pv_supplier_label': 'المورد: ',
      'pv_search_hint': 'بحث عن مورد بالاسم أو الهاتف...',
      'pv_no_suppliers': 'لا يوجد موردون',
      'pv_no_dues': 'لا توجد مستحقات لهذا المورد',
      'pv_account_label': 'حساب الصرف',
      'pv_note_hint': 'ملاحظة (اختياري)...',
      'pv_no_invoices':
          'لا توجد فواتير (أو لا يوجد اتصال).\nيمكنك إدخال سداد حر (دفعة من الحساب).',
      'pv_free_payment_label': 'مبلغ الدفعة الحرة (سداد من الحساب)',
      'pv_purchase_invoice_label': 'فاتورة مشتريات #',
      'pv_total_label': 'الإجمالي: ',
      'pv_remainder_label': 'المتبقي: {amount}',
      'pv_payment_amount_label': 'مبلغ الصرف: ',
      'pv_selected_invoices': '{count} فاتورة محددة',
      'pv_submit_button': 'تسجيل الصرف',
      // Receipt Voucher Screen
      'rv_offline_error':
          'أنت في وضع عدم الاتصال. لا يمكن جلب الفواتير. يرجى إدخال مبلغ السداد الحر.',
      'rv_customer_required': 'يرجى اختيار عميل أولاً',
      'rv_invoice_or_free_required':
          'يرجى اختيار فاتورة واحدة على الأقل أو إدخال مبلغ سداد حر',
      'rv_account_required': 'يرجى اختيار حساب القبض',
      'rv_no_shift_open': 'لا توجد وردية مفتوحة',
      'rv_confirm_title': 'تأكيد سند القبض',
      'rv_confirm_desc':
          'سيتم تسجيل سند قبض بقيمة\n{amount}\nمن العميل: {partner}',
      'rv_cancel': 'إلغاء',
      'rv_confirm': 'تأكيد',
      'rv_default_desc': 'سند قبض - ',
      'rv_save_print_success': 'تم الحفظ والطباعة للسند رقم ({id})',
      'rv_save_error': 'خطأ غير متوقع: ',
      'rv_screen_title': 'سند قبض',
      'rv_customer_label': 'العميل: ',
      'rv_search_hint': 'بحث عن عميل بالاسم أو الهاتف...',
      'rv_no_customers': 'لا يوجد عملاء',
      'rv_no_dues': 'لا توجد فواتير مستحقة لهذا العميل',
      'rv_account_label': 'حساب القبض',
      'rv_note_hint': 'ملاحظة (اختياري)...',
      'rv_no_invoices':
          'لا يمكن جلب الفواتير (أو لا توجد فواتير).\nيمكنك إدخال سداد حر (دفعة من الحساب).',
      'rv_free_payment_label': 'مبلغ الدفعة الحرة (سداد من الحساب)',
      'rv_sales_invoice_label': 'فاتورة رقم #',
      'rv_total_label': 'الإجمالي: ',
      'rv_remainder_label': 'المتبقي: {amount}',
      'rv_receipt_amount_label': 'مبلغ السداد: ',
      'rv_selected_invoices': '{count} فاتورة محددة',
      'rv_submit_button': 'تسجيل القبض',
      // General Payment Voucher Screen
      'gpv_choose_expense_account': 'اختر حساب المصروفات',
      'gpv_search_account_hint': 'ابحث عن حساب...',
      'gpv_account_code': 'كود: {code}',
      'gpv_expense_account_required':
          'الرجاء اختيار الحساب المستهدف (المصروفات)',
      'gpv_amount_required': 'الرجاء إدخال المبلغ',
      'gpv_invalid_amount': 'المبلغ غير صحيح',
      'gpv_cash_account_required': 'الرجاء اختيار حساب الصندوق/البنك',
      'gpv_undefined': 'غير محدد',
      'gpv_cash': 'نقدي',
      'gpv_save_print_success': 'تم إنشاء وطباعة سند الصرف بنجاح (رقم {id})',
      'gpv_save_error': 'حدث خطأ أثناء الحفظ: ',
      'gpv_cannot_save': 'تعذر الحفظ: ',
      'gpv_screen_title': 'سند صرف مباشر (مصروفات)',
      'gpv_target_account_label': 'الحساب المستهدف (المصروف)',
      'gpv_click_to_choose': 'اضغط لاختيار الحساب',
      'gpv_amount_label': 'المبلغ ',
      'gpv_statement_label': 'البيان / الملاحظات',
      'gpv_pay_from_account': 'دفع من حساب (الصندوق)',
      'gpv_save_button': 'حفظ السند المباشر',
      // General Receipt Voucher Screen
      'grv_choose_revenue_account': 'اختر حساب الإيرادات',
      'grv_revenue_account_required':
          'الرجاء اختيار الحساب المستهدف (الإيرادات)',
      'grv_save_print_success': 'تم إنشاء وطباعة سند القبض بنجاح (رقم {id})',
      'grv_screen_title': 'سند قبض مباشر (إيرادات)',
      'grv_target_account_label': 'الحساب المستهدف (الإيراد)',
      'grv_receive_to_account': 'قبض إلى حساب (الصندوق)',
      'grv_save_button': 'حفظ السند المباشر',
      // Daily Invoices Screen
      'di_fetch_error': 'فشل استرجاع فواتير اليوم من الخادم',
      'di_error_loading': 'حدث خطأ أثناء تحميل الفواتير: {error}',
      'di_screen_title': 'تقرير الفواتير اليومية والمستخدم',
      'di_total_sales': 'إجمالي المبيعات',
      'di_total_purchases': 'إجمالي المشتريات',
      'di_net_income': 'صافي الدخل (مبيعات - مشتريات)',
      'di_total_receipts': 'سندات قبض (وارد)',
      'di_total_payments': 'سندات صرف (صادر)',
      'di_net_cash': 'صافي النقدية (الدرج)',
      'di_tab_sales': 'المبيعات',
      'di_tab_purchases': 'المشتريات',
      'di_tab_receipts': 'سندات القبض',
      'di_tab_payments': 'سندات الصرف',
      'di_sales_invoices': 'مبيعات العملاء اليومية',
      'di_purchase_invoices': 'مشتريات الموردين اليومية',
      'di_receipt_vouchers': 'سندات القبض (محصلات)',
      'di_payment_vouchers': 'سندات الصرف (مدفوعات)',
      'di_daily_financial_split': 'الفصل المالي اليومي',
      'di_shift_financial_vouchers': 'السندات المالية للوردية',
      'di_no_invoices': 'لا توجد بيانات',
      'di_invoice_no': 'رقم الفاتورة: #{id}',
      'di_date': 'التاريخ: {date}',
      'di_time': 'الوقت: {time}',
      'di_net_amount': 'الصافي: {amount}',
      'di_voucher_no': 'رقم السند: #{id}',
      'di_voucher_amount': 'المبلغ: {amount}',
      'di_voucher_desc': 'البيان: {desc}',
      'di_print_button': 'طباعة التفاصيل',
      'di_print_success': 'تمت طباعة الفاتورة بنجاح',
      'di_print_error': 'فشل في طباعة الفاتورة',
      'di_invoice_details': 'تفاصيل الفاتورة',
      'di_partner_name': 'العميل/المورد: {name}',
      'di_discount': 'الخصم: {amount}',
      'di_paid': 'المدفوع: {amount}',
      'di_remainder': 'المتبقي: {amount}',
      'di_cashier': 'الكاشير: {name}',
      'di_invoice_items': 'عناصر الفاتورة:',
      'di_item_details':
          '{name}  -  الكمية: {qty}  -  السعر: {price}  -  الإجمالي: {total}',
      'di_total_col': 'الإجمالي',
      'di_price_col': 'السعر',
      'di_qty_col': 'الكمية',
      'di_item_col': 'الصنف',
      'di_grand_total': 'الإجمالي الكلي',
      'di_net_total': 'الصافي الكلي',
      'di_register_payment': 'تسجيل سداد دفعة',
      'di_reprint': 'إعادة طباعة',
      'di_close_popup': 'إغلاق',
      'di_payment_dialog_title': 'تسجيل سداد للفاتورة الآجلة',
      'di_payment_remaining': 'المتبقي غير المدفوع: {amount}',
      'di_payment_amount_label': 'مبلغ السداد المستلم',
      'di_payment_account_label': 'طريقة الدفع (الحساب)',
      'di_split_total_paid': 'إجمالي المسدد بالتجزئة:',
      'di_payment_method_label': 'طريقة الدفع',
      'di_payment_amount_single': 'المبلغ',
      'di_add_payment_method_btn': 'إضافة طريقة دفع أخرى',
      'di_invalid_split_amounts': 'يرجى تحديد مبالغ صحيحة لطرق الدفع',
      'di_single_payment_mode': 'دفع موحد',
      'di_cancel': 'إلغاء',
      'di_confirm_payment': 'تأكيد السداد',
      'print_payment_methods': 'وسائل الدفع',
      'print_payment_method': 'طريقة الدفع',
      'print_payment_cash': 'نقداً',
      'print_payment_credit': 'آجل',
      'print_payment_cash_credit': 'نقداً + آجل',
      'print_total_paid': 'إجمالي المدفوع',
      'print_balance_due': 'المتبقي آجل',
      'print_payment_breakdown': 'تفاصيل وسائل الدفع:',
      'di_invalid_payment': 'الرجاء إدخال مبلغ صحيح لا يتجاوز المتبقي',
      'di_payment_success': 'تم تسجيل السداد بنجاح وتحديث القيود المحاسبية!',
      'di_payment_fail': 'فشل تسجيل السداد: {error}',
      'di_payment_error': 'خطأ أثناء عملية السداد: {error}',
      'di_fetch_fail': 'فشل جلب تفاصيل الفاتورة من الخادم',
      'di_network_error': 'خطأ أثناء الاتصال بالشبكة: {error}',
      'cs_summary_fetch_error':
          'تعذر جلب ملخص الوردية. تأكد من وجود وردية مفتوحة.',
      'cs_data_load_error': 'خطأ في تحميل البيانات: {error}',
      'cs_enter_actual_cash': 'الرجاء إدخال النقدية الفعلية أولاً',
      'cs_offline_data_warning':
          'الرجاء التأكد من وجود اتصال بالإنترنت وحفظ كافة الفواتير والسندات قبل إغلاق الوردية.',
      'cs_confirm_close_title': 'تأكيد إغلاق الوردية',
      'cs_confirm_close_msg':
          'هل أنت متأكد من إغلاق الوردية الحالية؟\nلا يمكن التراجع عن هذه العملية.',
      'cs_cancel': 'إلغاء',
      'cs_close_shift': 'إغلاق الوردية',
      'cs_success': 'نجاح',
      'cs_close_success_msg': 'تم إغلاق الوردية بنجاح.',
      'cs_ok': 'موافق',
      'cs_error': 'خطأ',
      'cs_close_error_msg': 'حدث خطأ أثناء إغلاق الوردية: {error}',
      'cs_screen_title': 'إغلاق الوردية وتسليم النقدية',
      'cs_financial_summary': 'ملخص ماليات الوردية',
      'cs_starting_cash': 'العهدة الابتدائية',
      'cs_total_paid_sales': 'إجمالي مبيعات نقدية',
      'cs_total_paid_purchases': 'إجمالي مشتريات نقدية',
      'cs_total_receipts': 'إجمالي سندات قبض',
      'cs_total_payments': 'إجمالي سندات صرف',
      'cs_expected_cash': 'إجمالي النقدية المتوقعة',
      'cs_actual_cash': 'النقدية الفعلية (بالدرج)',
      'cs_enter_actual_cash_hint': 'أدخل النقدية الفعلية هنا',
      'cs_difference': 'العجز / الزيادة',
      'cs_close_print_btn': 'إغلاق وطباعة التقرير',
      'cs_unsynced_data_title': 'بيانات غير متزامنة',
      'cs_unsynced_data_msg':
          'يوجد {invoices} فواتير و {vouchers} سندات غير متزامنة.\nيجب مزامنتها مع الخادم قبل إغلاق الوردية.',
      'cs_sync_now': 'مزامنة الآن',
      'cs_sync_failed':
          'فشلت مزامنة بعض البيانات. يرجى التحقق من اتصالك بالإنترنت.',
      'cs_sync_success': 'تمت المزامنة بنجاح.',
      'cs_entered_cash': 'الكاش الختامي المُدخل: {amount}',
      'cs_expected_cash_msg': 'الكاش المتوقع: {amount}',
      'cs_difference_msg': 'الفرق: {amount}',
      'cs_confirm_close_with_print_msg':
          'هل أنت متأكد من إغلاق الوردية؟\nسيتم طباعة تقرير اليومية قبل الإغلاق.',
      'cs_yes_close_shift': 'نعم، أغلق الوردية',
      'cs_printing': 'جاري الطباعة...',
      'cs_closed_successfully': 'تم الإغلاق بنجاح',
      'cs_closing': 'جاري الإغلاق...',
      'cs_printer_error': 'فشل في الاتصال بالطابعة',
      'cs_cashier': 'الكاشير',
      'cs_open_time': 'وقت الفتح',
      'cs_status': 'الحالة',
      'cs_sales_summary': '📈 مبيعات الوردية',
      'cs_invoice_count': '{count} فاتورة',
      'cs_total_sales_label': 'إجمالي المبيعات',
      'cs_paid_sales_label': 'مُسدَّد نقداً',
      'cs_cash_sales_label': 'مبيعات نقدية (كاش)',
      'cs_knet_sales_label': 'مبيعات شبكة وبطاقات (K-Net)',
      'cs_credit_sales_label': 'آجل متبقي',
      'cs_purchases_summary': '📦 مشتريات الوردية',
      'cs_total_purchases_label': 'إجمالي المشتريات',
      'cs_paid_purchases_label': 'مُسدَّد نقداً',
      'cs_cash_purchases_label': 'مشتريات نقدية (كاش)',
      'cs_non_cash_purchases_label': 'مشتريات غير نقدية (بنك/أخرى)',
      'cs_credit_purchases_label': 'آجل متبقي',
      'cs_cash_drawer_calc': '💰 تسوية وجرد الكاش بالدرج',
      'cs_add_cash_sales': '(+) مبيعات كاش محصلة',
      'cs_sub_cash_purchases': '(-) مشتريات كاش مدفوعة',
      'cs_add_receipts': '(+) سندات قبض',
      'cs_subtract_payments': '(-) سندات صرف',
      'cs_loading_summary': 'جاري تحميل ملخص الوردية...',
      'cs_retry': 'إعادة المحاولة',
      'cs_shift_info': '📋 معلومات الوردية',
      'cs_invoices_count': 'عدد الفواتير',
      'cs_vouchers_summary': '🧾 السندات المالية',
      'cs_add_paid_sales': '(+) مبيعات كاش محصلة',
      'cs_sub_paid_purchases': '(-) مشتريات كاش مدفوعة',
      'cs_sub_payments': '(-) سندات صرف',
      // Close Shift Screen
      'cs_error_fetch_summary':
          'تعذر جلب ملخص الوردية. تأكد من وجود وردية مفتوحة.',
      'cs_error_load_data': 'خطأ في تحميل البيانات: {error}',
      'cs_no_open_shift': 'لا توجد وردية مفتوحة',
      'cs_unsynced_data_content':
          'يوجد {invoices} فواتير و {vouchers} سندات غير متزامنة.\nيجب مزامنتها مع الخادم قبل إغلاق الوردية.',
      'cs_ending_cash_entered': 'الكاش الختامي المُدخل: {amount}',
      'cs_confirm_close_content':
          'هل أنت متأكد من إغلاق الوردية؟\nسيتم طباعة تقرير اليومية قبل الإغلاق.',
      'cs_yes_close': 'نعم، أغلق الوردية',
      'cs_close_success': 'تم إغلاق الوردية بنجاح ✓',
      'cs_close_failed': 'فشل إغلاق الوردية: {error}',
      'cs_shift_info_card': '📋 معلومات الوردية',
      'cs_sales_card': '📈 مبيعات الوردية',
      'cs_invoices_count_val': '{count} فاتورة',
      'cs_total_sales': 'إجمالي المبيعات',
      'cs_paid_cash': 'مُسدَّد نقداً',
      'cs_credit_remainder': 'آجل متبقي',
      'cs_purchases_card': '📦 مشتريات الوردية',
      'cs_total_purchases': 'إجمالي المشتريات',
      'cs_vouchers_card': '🧾 السندات المالية',
      'cs_total_receipt_vouchers': 'إجمالي سندات القبض',
      'cs_total_payment_vouchers': 'إجمالي سندات الصرف',
      'cs_cash_settlement_card': '💰 تسوية الكاش',
      'cs_plus_paid_sales': '+ مبيعات مسددة',
      'cs_minus_paid_purchases': '- مشتريات مسددة',
      'cs_plus_receipt_vouchers': '+ سندات قبض',
      'cs_minus_payment_vouchers': '- سندات صرف',
      'cs_equals_expected_cash': '= الكاش المتوقع',
      'cs_print_and_close': 'طباعة التقرير وإغلاق الوردية',
      // Printer Settings Screen
      'ps_save_success': 'تم حفظ إعدادات الطابعة بنجاح!',
      'ps_save_failed': 'فشل في حفظ الإعدادات',
      'ps_test_simulated':
          'تمت محاكاة الطباعة التجريبية بنجاح في الكونسول (الطباعة الفعلية معطلة)',
      'ps_test_success': 'تمت الطباعة التجريبية بنجاح على الطابعة المحددة!',
      'ps_test_failed':
          'فشل في طباعة الفاتورة التجريبية، يرجى التحقق من اتصال وإعدادات الطابعة',
      'ps_screen_title': 'إعدادات الطابعة الحرارية',
      'ps_config_title': 'تكوين طابعة إيصالات الكاشير (POS)',
      'ps_synced': 'مزامنة نشطة مع السيرفر',
      'ps_offline': 'حفظ محلي فقط (أوفلاين)',
      'ps_conn_type': 'نوع الاتصال الطابعة',
      'ps_conn_none': 'غير متصلة (تعطيل الطباعة)',
      'ps_conn_network': 'شبكي (Network IP Printer)',
      'ps_conn_bluetooth': 'بلوتوث (Bluetooth Printer)',
      'ps_ip_label': 'عنوان IP الطابعة (مثال: 192.168.1.100)',
      'ps_port_label': 'منفذ الاتصال (Port - افتراضي 9100)',
      'ps_bt_device': 'جهاز طابعة البلوتوث',
      'ps_bt_clear': 'إلغاء التحديد',
      'ps_bt_selected': 'الطابعة المحددة حالياً للتشغيل',
      'ps_bt_scan_searching': 'جاري البحث عن أجهزة...',
      'ps_bt_scan_button': 'البحث عن الطابعات المتوفرة (Scan)',
      'ps_bt_scan_desc': 'جاري فحص النطاق والبحث عن أجهزة بلوتوث نشطة...',
      'ps_bt_found': 'الطابعات التي تم العثور عليها:',
      'ps_network_mode_label': 'نمط طباعة الشبكة (Network Engine)',
      'ps_network_mode_direct': 'النص المباشر (تلقائي - النظام القديم)',
      'ps_network_mode_raster':
          'طباعة صورية عالية الدقة (صورة Canvas - للغة العربية والشعار)',
      'ps_network_mode_desc':
          'اختر الطباعة الصورية عند توصيل طابعة شبكة POS 80 لحل مشاكل الحروف العربية والشعار على هذا الجهاز فقط.',
      'ps_test_print_btn': 'طباعة تجريبية',
      'ps_save_btn': 'حفظ الإعدادات',

      // Partner Selection Screen
      'ps_title_customer': 'اختيار العميل',
      'ps_title_supplier': 'اختيار المورد',
      'ps_fetch_customer_failed': 'فشل جلب قائمة العملاء من الخادم',
      'ps_fetch_supplier_failed': 'فشل جلب قائمة الموردين من الخادم',
      'ps_search_customer_hint': 'البحث باسم العميل، الهاتف أو رقم الحساب...',
      'ps_search_supplier_hint': 'البحث باسم المورد، الهاتف أو رقم الحساب...',
      'ps_no_results_supplier': 'لا يوجد موردين مطابقين للبحث',
      'ps_general_cash_label': 'نقدي عام',
      'ps_general_cash_sub': 'عميل عام (مبيعات سريعة)',
      'ps_general_cash_desc': 'نقدي مباشر',
      'ps_no_account_code': 'لا يوجد',
      'ps_account_code_label': 'رقم الحساب المالي: ',
      'ps_phone_label': 'الهاتف: ',
      'ps_balance_credit': 'مستحق له',
      'ps_balance_debit': 'مستحق عليه',
      'ps_unknown_partner': 'شريك غير معروف',
      'ps_retry': 'إعادة المحاولة',
      'ps_conn_error': 'حدث خطأ في الاتصال بالشبكة: ',

      // Stock Take Screen
      'st_empty_cart_error': 'يرجى إضافة أصناف أولاً',
      'st_save_success_print_failed':
          'تم حفظ الجرد بنجاح برقم ({id}) ولكن فشلت الطباعة',
      'st_save_success_printing':
          'تم حفظ الجرد بنجاح برقم ({id}) وجاري الطباعة',
      'st_save_failed': 'فشل حفظ الجرد كمسودة',
      'st_screen_title': 'جرد المخزون (مسودة)',
      'st_clear_tooltip': 'مسح القائمة',
      'st_warehouse_label': 'مستودع الجرد:',
      'st_warehouse_locked_warn':
          'تم قفل تعديل مستودع الجرد بسبب وجود عناصر في السلة',
      'st_cart_empty_hint': 'السلة فارغة. ابدأ بمسح أو إضافة أصناف',
      'st_item_barcode': 'الباركود: ',
      'st_item_unit': ' | الوحدة: ',
      'st_item_cost': ' | التكلفة: ',
      'st_system_qty': 'الكمية الدفترية',
      'st_actual_qty': 'الكمية الفعلية',
      'st_diff_value': 'قيمة الفرق',
      'st_difference': 'الفرق',
      'st_total_diff_value': 'إجمالي قيمة الفروقات:',
      'st_notes_hint': 'ملاحظات الجرد الإضافية...',
      'st_save_print_btn': 'حفظ وطباعة مسودة الجرد',

      // Wastage Screen
      'wt_empty_cart_error': 'يرجى إضافة أصناف أولاً',
      'wt_save_success_print_failed':
          'تم حفظ الهالك بنجاح برقم ({id}) ولكن فشلت الطباعة',
      'wt_save_success_printing':
          'تم حفظ الهالك بنجاح برقم ({id}) وجاري الطباعة',
      'wt_save_failed': 'فشل حفظ الهالك كمسودة',
      'wt_screen_title': 'إهلاك بضاعة (الهالك)',
      'wt_clear_tooltip': 'مسح القائمة',
      'wt_warehouse_label': 'المستودع المالي:',
      'wt_warehouse_locked_warn':
          'تم قفل تعديل المستودع بسبب وجود عناصر في السلة',
      'wt_cart_empty_hint': 'السلة فارغة. ابدأ بمسح أو إضافة أصناف',
      'wt_item_barcode': 'الباركود: ',
      'wt_item_unit': ' | الوحدة: ',
      'wt_cost_price': 'سعر التكلفة',
      'wt_quantity': 'الكمية',
      'wt_total_cost': 'إجمالي التكلفة:',
      'wt_total_wastage_value': 'إجمالي قيمة الهالك:',
      'wt_notes_hint': 'ملاحظات إضافية...',
      'wt_save_print_btn': 'حفظ وطباعة المسودة',

      // Temporary Order / Delivery Info Screen
      'temp_order_title_general': 'بيانات التوصيل والطلب المؤقت',
      'temp_order_title_customer': 'تحديد موعد التوصيل للعميل',
      'temp_order_skip_general': 'تخطي والمتابعة كنقدي عام مباشر',
      'temp_order_skip_customer': 'تخطي والمتابعة بدون بيانات توصيل',
      'temp_order_cust_info_title': 'معلومات الزبون المؤقت',
      'temp_order_cust_name_label': 'اسم الزبون / العميل',
      'temp_order_phone_label': 'رقم الهاتف',
      'temp_order_address_label': 'عنوان التوصيل بالتفصيل',
      'temp_order_delivery_schedule_title': 'موعد التسليم والملاحظات',
      'temp_order_select_time': 'تحديد الوقت',
      'temp_order_select_date': 'تحديد التاريخ',
      'temp_order_notes_label': 'ملاحظات إضافية حول الطلب والتوصيل',
      'temp_order_proceed_btn': 'متابعة إلى سلة المنتجات ⬅',
      'temp_order_validation_error':
          'الرجاء إدخال بعض البيانات أو اختيار تخطي للمتابعة بنقدي عام مباشر',
      // Split Payment Dialog
      'split_paid_now': 'المسدد الآن:',
      'split_remainder_credit': 'المتبقي (آجل تلقائياً):',
      'split_payment_account': 'طريقة الدفع (الحساب)',
      'split_amount_paid': 'المبلغ المسدد',
      'split_add_another_method': 'إضافة طريقة دفع أخرى',
      'split_confirm_and_save': 'تأكيد وحفظ الفاتورة',
      'split_cancel': 'إلغاء',
      'split_valid_amounts_warn': 'يرجى تحديد مبالغ صحيحة لطرق الدفع',
      // Invoice Lookup & Extra Discount
      'home_invoice_lookup': 'البحث عن فاتورة',
      'home_invoice_lookup_sub': 'استعلام برقم الفاتورة مع الطباعة السريعة',
      'inv_lookup_title': 'البحث عن فاتورة (مبيعات / مشتريات)',
      'inv_lookup_by_id': 'البحث عن الفاتورة برقم الفاتورة:',
      'inv_lookup_hint': 'أدخل رقم الفاتورة (مثال: 101)',
      'inv_lookup_search_btn': 'بحث',
      'inv_lookup_reprint_btn': 'طباعة الإيصال 🖨️',
      'inv_lookup_reprint_full': 'إعادة طباعة الفاتورة حرارياً 🖨️',
      'inv_lookup_delivery_title': 'بيانات التوصيل والدليفري (Delivery Info):',
      'inv_lookup_items_title': 'أصناف وبنود الفاتورة:',
      'inv_lookup_not_found': 'الفاتورة غير موجودة بالخادم',
      'inv_lookup_invalid_id': 'يرجى إدخال رقم فاتورة صحيح',
      'inv_lookup_loading': 'جاري البحث عن الفاتورة واسترجاع التفاصيل...',
      'inv_lookup_empty_hint':
          'أدخل رقم الفاتورة واضغط على بحث لإظهار كافة التفاصيل والبيانات والطباعة السريعة',
      'inv_lookup_sales_badge': 'فاتورة مبيعات',
      'inv_lookup_purchase_badge': 'فاتورة مشتريات',
      'inv_lookup_reprint_success': 'تمت إعادة طباعة الفاتورة بنجاح',
      'inv_lookup_reprint_failed': 'فشلت عملية الطباعة الحرارية',
      'inv_lookup_partner_cust': 'العميل:',
      'inv_lookup_partner_supp': 'المورد:',
      'inv_lookup_general_cash': 'عام / سند مباشر',
      'inv_lookup_inv_date': 'تاريخ الفاتورة:',
      'inv_lookup_warehouse': 'المستودع:',
      'inv_lookup_cashier': 'المستخدم / الكاشير:',
      'inv_lookup_payment_acc': 'حساب الدفع:',
      'inv_lookup_delivery_schedule': 'موعد التسليم:',
      'inv_lookup_notes': 'ملاحظات الفاتورة:',
      'inv_lookup_col_item': 'الصنف',
      'inv_lookup_col_qty': 'الكمية',
      'inv_lookup_col_price': 'السعر',
      'inv_lookup_col_total': 'الإجمالي',
      'inv_lookup_unknown_item': 'صنف غير معروف',
      'inv_lookup_gross_total': 'الإجمالي قبل الخصم (Gross):',
      'inv_lookup_discount': 'خصم الفاتورة (Discount):',
      'inv_lookup_net_total': 'الصافي النهائي (Net Total):',
      'inv_lookup_paid_amount': 'المبلغ المدفوع (Paid):',
      'inv_lookup_remainder': 'المبلغ المتبقي (Remainder):',
      'inv_lookup_credit': 'آجل',
      'inv_lookup_paid_status': 'مدفوع',
      'inv_lookup_split_payments': 'سجل دفعات',
      'inv_lookup_split_payments_card': 'Split Payments',
      'inv_lookup_cash': 'نقداً / كاش',
      'pos_extra_discount': 'خصم إضافي:',
      'pos_extra_discount_hint': '0.000',
      // In-App Auto Update Dialog
      'update_title': 'تحديث جديد متوفر!',
      'update_version_label': 'الإصدار:',
      'update_current_label': 'الحالي:',
      'update_whats_new': 'الجديد في هذا التحديث:',
      'update_default_notes': '• تحسينات شاملة واستقرار في الأداء وسرعة المعالجة.',
      'update_now_btn': 'تحديث الآن ⚡',
      'update_later_btn': 'لاحقاً',
      'update_downloading_connecting': 'جاري الاتصال بالسيرفر وتنزيل التحديث...',
      'update_downloading_progress': 'جاري التنزيل:',
      'update_download_completed': 'اكتمل التنزيل بنجاح 100%! جاري تشغيل التثبيت... 🚀',
      'update_installer_opened': 'تم فتح ملف التثبيت! يرجى تأكيد التثبيت على شاشة الجهاز.',
      'update_install_failed': 'تعذر فتح التثبيت التلقائي.',
      'update_install_permission_warn': 'يرجى التأكد من السماح للتطبيق بتثبيت التطبيقات من هذا المصدر في إعدادات الهاتف.',
      'update_already_latest': 'أنت تستخدم أحدث إصدار من التطبيق بالفعل! 🎉',
      'settings_check_updates': 'التحقق من وجود تحديثات',
      'settings_check_updates_desc': 'فحص السيرفر للتحقق من توفر إصدار أحدث للتطبيق',
    },
    'en': {
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'General Settings',
      'home': 'Home',
      // Login Screen
      'login_title': 'Login',
      'login_username_hint': 'Username',
      'login_password_hint': 'Password',
      'login_button': 'Enter',
      'login_empty_error': 'Please enter username and password',
      'login_failed_fallback': 'Login failed',
      // License Screen
      'license_whatsapp_error':
          'Could not open WhatsApp, please message 55381505 manually',
      'license_copied': 'Device HWID copied to clipboard successfully!',
      'license_title': 'Vegtablity POS Protection',
      'license_checking': 'Checking device license...',
      'license_expired_title': 'Subscription Expired!',
      'license_expired_desc':
          'Sorry, your subscription for this device expired on ',
      'license_expired_desc_2':
          '.\nPlease renew your subscription with technical support to continue.',
      'license_error_title': 'Connection Error!',
      'license_inactive_title': 'License Inactive!',
      'license_inactive_desc':
          'This device is registered but the license is temporarily suspended.\nPlease contact technical support for activation.',
      'license_unregistered_title': 'Unregistered Device!',
      'license_unregistered_desc':
          'The hardware ID of this device is not registered in our system.\nPlease send your device HWID to technical support for registration.',
      'license_hwid_label': 'Your Device HWID',
      'license_support_title': 'Technical Support & Licensing',
      'license_phone_label': 'Phone:',
      'license_send_whatsapp': 'Send HWID via WhatsApp',
      'license_info_button': 'More Info',
      'license_retry_button': 'Retry Check',
      // Shift Screen
      'shift_open_error_empty': 'Please enter a valid starting cash amount',
      'shift_open_failed_fallback': 'Failed to open shift',
      'shift_checking_status': 'Checking shift status...',
      'shift_wait_data': 'Please wait while loading data from the server',
      'shift_new_title': 'Open New Shift',
      'shift_confirm_cash': 'Confirm Cashier Starting Cash',
      'shift_cash_label': 'Amount (Cash)',
      'shift_open_button': 'Open Shift & Start Work',
      'shift_select_warehouse': 'Select Warehouse for Shift',
      'shift_warehouse_label': 'Warehouse',
      'shift_warehouse_error':
          'Please select a warehouse before opening the shift',
      // Home Screen
      'home_title': 'Smart Cashier System (POS)',
      'home_server_status': 'Server Status: ',
      'home_welcome': 'Welcome: ',
      'home_active_shift': 'Shift No: #',
      'home_no_active_shift': 'No Active Shift',
      'home_developed_by': 'Developed by Mohamed Ragab',
      'home_printer_settings': 'Thermal Printer Settings',
      'home_open_cash_drawer': '💰 Open Cash Drawer',
      'home_daily_invoices': 'Daily Invoices Report',
      'home_close_shift': 'Close Current Shift',
      'home_receipt_voucher': 'Cash Receipt Voucher',
      'home_receipt_voucher_sub': 'Direct cash collection from customer',
      'home_payment_voucher': 'Cash Payment Voucher',
      'home_payment_voucher_sub': 'Direct cash payment to supplier',
      'home_drawer_stocktake': 'Stock Take (Draft)',
      'home_drawer_wastage': 'Wastage / Damaged Goods',
      'home_drawer_recipes': 'Product Recipes & Manufacturing',
      'home_classic_stocktake': 'Stock Take (Draft)',
      'home_classic_wastage': 'Wastage / Damaged Goods',
      'home_daily_orders': 'Daily Delivery Orders',
      'home_recipes': 'Product Recipes & Manufacturing',
      'home_classic_recipes': 'Product Recipes',
      'home_no_enabled_cards_warn':
          'No cards enabled. Please enable cards from settings.',
      'home_premium_new_invoice': 'New Sales Invoice',
      'home_premium_new_purchase': 'New Purchase Invoice',
      'home_premium_customer_sales': 'Customer Sales Quotes',
      'home_premium_supplier_purchases': 'Supplier Purchase Quotes',
      'home_premium_customer_receipts': 'Customer Receipt Vouchers',
      'home_premium_supplier_payments': 'Supplier Payment Vouchers',
      'settings_allow_edit_unposted_invoices': 'Enable Editing Unposted Invoices (This Device)',
      'settings_allow_edit_unposted_invoices_desc':
          'Allow reopening and editing unposted sales & purchase invoices from lookup and daily reports',
      'inv_lookup_edit_btn': 'Edit Invoice ✏️',
      'inv_lookup_posted_no_edit': 'Invoice is posted and cannot be edited',
      'pos_edit_mode_title': 'Invoice Edit Mode',
      'pos_editing_invoice_sales': 'Editing Sales Invoice #{id}',
      'pos_editing_invoice_purchase': 'Editing Purchase Invoice #{id}',
      'pos_save_changes_btn': 'Save Changes',
      'pos_edit_success': 'Invoice updated and saved successfully!',
      'di_edit_invoice_btn': 'Edit Invoice ✏️',
      // Printer Settings Screen
      'ps_title': 'Printer Settings',
      'ps_connection_type': 'Connection Type:',
      'ps_type_none': 'Disabled (No Printer)',
      'ps_type_bluetooth': 'Bluetooth',
      'ps_type_network': 'Network (LAN / Wi-Fi)',
      'ps_ip_label': 'Printer IP Address',
      'ps_port_label': 'Port',
      'ps_bt_device_label': 'Paired Bluetooth Device',
      'ps_bt_select_hint': 'Select Bluetooth Printer',
      'ps_paper_size_label': 'Paper Size (Width)',
      'ps_paper_80mm': '80 mm (POS Standard)',
      'ps_paper_58mm': '58 mm (Portable/Mini)',
      'ps_copies_label': 'Number of Copies',
      'ps_save_success': 'Printer settings saved successfully',
      'ps_save_failed': 'Failed to save settings',
      'ps_test_printing': 'Printing test receipt...',
      'ps_test_success': 'Test receipt sent to printer',
      'ps_test_failed': 'Failed to print test receipt',
      'ps_bt_scan_button': 'Scan Available Printers',
      'ps_bt_scan_desc': 'Scanning range for active Bluetooth devices...',
      'ps_bt_found': 'Found Printers:',
      'ps_network_mode_label': 'Network Print Engine',
      'ps_network_mode_direct': 'Direct ESC/POS Text',
      'ps_network_mode_raster': 'High Resolution HD Canvas Image',
      'ps_network_mode_desc':
          'Select raster mode for 80mm network printers to solve Arabic alignment and logo issues.',
      'ps_test_print_btn': 'Test Print',
      'ps_save_btn': 'Save Settings',
      'home_barcode_print': 'Print Barcode Labels',
      'settings_show_barcode_print': 'Show Barcode Print in Sidebar',
      'barcode_print_title': 'Barcode Label Printing',
      'barcode_search_hint': 'Search by product name or barcode...',
      'barcode_copies_title': 'Print Copies Count',
      'barcode_print_button': 'Print Barcode Labels 🖨️',
      'barcode_type_regular': 'Regular Item',
      'barcode_type_manufactured': 'Manufactured',
      'barcode_type_intermediate': 'Intermediate',
      'barcode_print_success': 'Barcode label printed successfully',
      'barcode_print_failed': 'Failed to print barcode label',
      'barcode_select_product_prompt': 'Tap any product to select and specify print copies',
      'barcode_preview_title': 'Barcode Label Preview',
      'barcode_category_all': 'All',
      // Partner Selection Screen
      'ps_title_customer': 'Select Customer',
      'ps_title_supplier': 'Select Supplier',
      'ps_fetch_customer_failed': 'Failed to fetch customer list from server',
      'ps_fetch_supplier_failed': 'Failed to fetch supplier list from server',
      'ps_search_customer_hint':
          'Search customer by name, phone or account code...',
      'ps_search_supplier_hint':
          'Search supplier by name, phone or account code...',
      'ps_no_results_supplier': 'No matching suppliers found',
      'ps_general_cash_label': 'General Cash',
      'ps_general_cash_sub': 'General customer (Quick Sales)',
      'ps_general_cash_desc': 'Direct Cash',
      'ps_no_account_code': 'None',
      'ps_account_code_label': 'Financial Account Code: ',
      'ps_phone_label': 'Phone: ',
      'ps_balance_credit': 'Credit Balance',
      'ps_balance_debit': 'Debit Balance',
      'ps_unknown_partner': 'Unknown Partner',
      'ps_retry': 'Retry',
      'ps_conn_error': 'Network connection error: ',
      // Stock Take Screen
      'st_empty_cart_error': 'Please add items first',
      'st_save_success_print_failed':
          'Stock take draft saved #{id} but printing failed',
      'st_save_success_printing': 'Stock take draft saved #{id} and printing',
      'st_save_failed': 'Failed to save stock take draft',
      'st_screen_title': 'Stock Take (Draft)',
      'st_clear_tooltip': 'Clear List',
      'st_warehouse_label': 'Stock Take Warehouse:',
      'st_warehouse_locked_warn':
          'Warehouse selection locked because cart contains items',
      'st_cart_empty_hint': 'Cart is empty. Scan or add items to begin',
      'st_item_barcode': 'Barcode: ',
      'st_item_unit': ' | Unit: ',
      'st_item_cost': ' | Cost: ',
      'st_system_qty': 'Book Qty',
      'st_actual_qty': 'Actual Qty',
      'st_diff_value': 'Diff Value',
      'st_difference': 'Difference',
      'st_total_diff_value': 'Total Diff Value:',
      'st_notes_hint': 'Additional stock take notes...',
      'st_save_print_btn': 'Save & Print Stock Take Draft',
      // Wastage Screen
      'wt_empty_cart_error': 'Please add items first',
      'wt_save_success_print_failed':
          'Wastage draft saved #{id} but printing failed',
      'wt_save_success_printing': 'Wastage draft saved #{id} and printing',
      'wt_save_failed': 'Failed to save wastage draft',
      'wt_screen_title': 'Damaged Goods / Wastage',
      'wt_clear_tooltip': 'Clear List',
      'wt_warehouse_label': 'Financial Warehouse:',
      'wt_warehouse_locked_warn':
          'Warehouse selection locked because cart contains items',
      'wt_cart_empty_hint': 'Cart is empty. Scan or add items to begin',
      'wt_item_barcode': 'Barcode: ',
      'wt_item_unit': ' | Unit: ',
      'wt_cost_price': 'Cost Price',
      'wt_quantity': 'Quantity',
      'wt_total_cost': 'Total Cost:',
      'wt_total_wastage_value': 'Total Wastage Value:',
      'wt_notes_hint': 'Additional notes...',
      'wt_save_print_btn': 'Save & Print Draft',
      // Temporary Order / Delivery Info Screen
      'temp_order_title_general': 'Delivery Info & Temporary Order',
      'temp_order_title_customer': 'Set Delivery Schedule for Customer',
      'temp_order_skip_general': 'Skip & proceed as direct general cash',
      'temp_order_skip_customer': 'Skip & proceed without delivery info',
      'temp_order_cust_info_title': 'Temporary Customer Info',
      'temp_order_cust_name_label': 'Customer Name',
      'temp_order_phone_label': 'Phone Number',
      'temp_order_address_label': 'Detailed Delivery Address',
      'temp_order_delivery_schedule_title': 'Delivery Schedule & Notes',
      'temp_order_select_time': 'Select Time',
      'temp_order_select_date': 'Select Date',
      'temp_order_notes_label': 'Additional Order & Delivery Notes',
      'temp_order_proceed_btn': 'Proceed to Cart ⬅',
      'temp_order_validation_error':
          'Please enter some info or choose skip to proceed as general cash',
      // Split Payment Dialog
      'split_paid_now': 'Paid Now:',
      'split_remainder_credit': 'Remaining (Credit automatically):',
      'split_payment_account': 'Payment Method (Account)',
      'split_amount_paid': 'Amount Paid',
      'split_add_another_method': 'Add another payment method',
      'split_confirm_and_save': 'Confirm and Save Invoice',
      'split_cancel': 'Cancel',
      'split_valid_amounts_warn':
          'Please enter valid amounts for payment methods',
      // Invoice Lookup & Extra Discount
      'home_invoice_lookup': 'Search Invoice',
      'home_invoice_lookup_sub': 'Lookup by Invoice ID with Quick Printing',
      'inv_lookup_title': 'Search Invoice ',
      'inv_lookup_by_id': 'Search Invoice by ID:',
      'inv_lookup_hint': 'Enter Invoice ID (e.g. 101)',
      'inv_lookup_search_btn': 'Search',
      'inv_lookup_reprint_btn': 'Print Receipt 🖨️',
      'inv_lookup_reprint_full': 'Re-print Invoice 🖨️',
      'inv_lookup_delivery_title': 'Delivery Info:',
      'inv_lookup_items_title': 'Invoice Line Items:',
      'inv_lookup_not_found': 'Invoice not found on server',
      'inv_lookup_invalid_id': 'Please enter a valid Invoice ID',
      'inv_lookup_loading': 'Searching for invoice and fetching details...',
      'inv_lookup_empty_hint':
          'Enter invoice number and tap search to show complete details and quick print',
      'inv_lookup_sales_badge': 'Sales Invoice',
      'inv_lookup_purchase_badge': 'Purchase Invoice',
      'inv_lookup_reprint_success': 'Invoice re-printed successfully',
      'inv_lookup_reprint_failed': 'Thermal printing failed',
      'inv_lookup_partner_cust': 'Customer:',
      'inv_lookup_partner_supp': 'Supplier:',
      'inv_lookup_general_cash': 'General / Direct Cash',
      'inv_lookup_inv_date': 'Invoice Date:',
      'inv_lookup_warehouse': 'Warehouse:',
      'inv_lookup_cashier': 'User / Cashier:',
      'inv_lookup_payment_acc': 'Payment Account:',
      'inv_lookup_delivery_schedule': 'Delivery Schedule:',
      'inv_lookup_notes': 'Invoice Notes:',
      'inv_lookup_col_item': 'Item',
      'inv_lookup_col_qty': 'Qty',
      'inv_lookup_col_price': 'Price',
      'inv_lookup_col_total': 'Total',
      'inv_lookup_unknown_item': 'Unknown Item',
      'inv_lookup_gross_total': 'Gross Total:',
      'inv_lookup_discount': 'Invoice Discount:',
      'inv_lookup_net_total': 'Net Total:',
      'inv_lookup_paid_amount': 'Paid Amount:',
      'inv_lookup_remainder': 'Remaining Amount:',
      'inv_lookup_credit': 'Credit',
      'inv_lookup_paid_status': 'Paid',
      'inv_lookup_split_payments': 'Split Payments',
      'inv_lookup_split_payments_card': 'Split Payments',
      'inv_lookup_cash': 'Cash',
      'pos_extra_discount': 'Extra Discount:',
      'pos_extra_discount_hint': '0.000',
      'cd_open_success': 'Cash drawer opened successfully',
      'cd_open_failed': 'Could not open cash drawer in current printer mode',
      'home_logout': 'Logout',
      'home_offline_invoices_1': 'You have ',
      'home_offline_invoices_2': ' offline invoice(s) waiting to be synced.',
      'home_sync_success': 'Sync Successful',
      'home_sync_failed': 'Sync Failed',
      'home_sync_now': 'Sync Now',
      'home_offline_vouchers_2': ' offline voucher(s) waiting to be synced.',
      'home_sync': 'Sync',
      'home_classic_new_invoice': 'New Sales Invoice',
      'home_classic_new_purchase': 'New Purchase Invoice',
      'home_classic_manage_partners': 'Manage Suppliers/Customers',
      'home_classic_sales_quote': 'Load Sales Quote',
      'home_premium_receipts_sub': 'Receipt Vouchers',
      'home_premium_payments_sub': 'Payment Vouchers',
      'settings_show_daily_orders': 'Show Daily Orders Card',
      // Settings Screen
      'settings_home_modules_title': 'Customize Home Screen Cards',
      'settings_home_modules_desc':
          'Select shortcuts and cards to display on the Home Screen:',
      'settings_save_success':
          'New layout saved and Home Screen updated successfully',
      'settings_save_error':
          'An error occurred while saving settings. Please try again later',
      'settings_layout_title': 'Home Screen Layout & Design',
      'settings_layout_desc':
          'Choose the interface you want to work with. The preference is loaded automatically on startup.',
      'settings_classic_title': 'Classic Layout (Default)',
      'settings_classic_desc':
          'The original interface that provides quick access to direct manual sales, supplier management, and public offers.',
      'settings_premium_title': 'Partners Offers Layout (New)',
      'settings_premium_desc':
          'A POS interface fully dedicated to active partner offers (purchases/sales), preventing products outside the offer and supporting cash or credit payments.',
      // POS Screen
      'pos_barcode_simulator_title': 'Barcode & Product Simulator',
      'pos_barcode_simulator_input': 'Enter barcode or product name',
      'pos_cancel': 'Cancel',
      'pos_add_to_cart': 'Add to Cart',
      'pos_sales_title': 'Point of Sale',
      'pos_purchases_title': 'Purchase Invoice',
      'pos_barcode_input': 'Enter barcode or product name manually',
      'pos_empty_cart':
          'Cart is empty. Scan or enter product barcodes to start.',
      'pos_item_price': 'Price: ',
      'pos_item_quantity': ' | Qty: ',
      'pos_item_discount': 'Item Discount',
      'pos_gross_total': 'Gross Total',
      'pos_total_discount': 'Discount',
      'pos_net_total': 'Net Total',
      'pos_save_success_warn':
          'Invoice ({id}) saved but printer connection failed',
      'pos_save_success_ok': 'Invoice ({id}) saved and printed successfully',
      'pos_print_status_printed': 'Printed',
      'pos_print_status_virtual': 'Virtual',
      'pos_print_status_failed': 'Print Failed',
      'pos_save_failed': 'Failed to save invoice',
      'pos_total': 'Total',
      'pos_pay_print': 'Pay & Print (F12)',
      'pos_split_payment': 'Split Payment',
      'pos_sales_title_with_partner': 'Sales Invoice - {name}',
      'pos_purchase_title_with_partner': 'Purchase Invoice - {name}',
      'pos_purchase_title': 'New Purchase Invoice',
      'pos_catalog_tooltip': 'View Product Catalog',
      'pos_customer': 'Customer',
      'pos_supplier': 'Supplier',
      'pos_cash_general': 'General Cash',
      'pos_change_customer': 'Change Customer',
      'pos_change_supplier': 'Change Supplier',
      'pos_unrecognized_title': 'New Unrecognized Item',
      'pos_barcode_label': 'Barcode: {barcode}',
      'pos_sale_price': 'Selling Price',
      'pos_save_and_add': 'Save & Add',
      'pos_invalid_price_error': 'Please enter a valid price greater than zero',
      'pos_quick_add_success': 'Item registered and added successfully',
      'pos_quick_add_error': 'An error occurred during registration',
      'pos_catalog_title': 'Product Catalog',
      'pos_catalog_refresh': 'Refresh Products',
      'pos_catalog_no_products': 'No active products currently',
      'pos_catalog_all': 'All',
      'pos_added_to_cart': '{name} added to cart',
      'pos_trans_type': 'Transaction Type',
      'pos_credit_mode': 'Credit / On Account',
      'pos_cash_mode': 'Cash / Paid',
      'pos_payment_account': 'Payment Method / Account',
      'pos_save_and_print': 'Save Invoice & Print',
      'pos_total_due': 'Total Due',
      'pos_finish_order': 'Finish Order',
      // Partner Offers Screen
      'po_error_fetch_partners': 'Failed to retrieve active partners data',
      'po_error_network': 'Network error occurred: ',
      'po_loading_quote': 'Loading offer details and approved prices...',
      'po_no_active_quote':
          'No active or approved quote for this partner currently!',
      'po_error_loading_quote': 'Error loading quote: ',
      'po_sales_partners_title': 'Active Sales Offer Customers',
      'po_purchases_partners_title': 'Active Purchase Offer Suppliers',
      'po_search_hint': 'Search by partner name or phone...',
      'po_retry': 'Retry',
      'po_no_partners_found': 'No active partners match the search currently.',
      'po_no_phone': 'No Phone',
      'po_no_address': 'Address not specified',
      // Partner Billing Screen
      'pb_unknown_item': 'Unknown Item',
      'pb_item_piece': 'Pcs',
      'pb_item_added': 'Added: ',
      'pb_alert_unapproved': 'Alert - Unapproved Item',
      'pb_alert_unapproved_desc':
          'The barcode ({barcode}) is not listed in the active approved quote for this partner!\n\nAdding products outside the offer is prohibited.',
      'pb_ok': 'OK',
      'pb_scan_camera_title': 'Scan Barcode via Camera',
      'pb_scan_camera_hint': 'Point the camera at the item barcode',
      'pb_cart_empty_error': 'Cart is empty! Please add products first',
      'pb_offer_notes': 'Partner Offers Invoice - Quote No. ',
      'pb_save_success':
          'Invoice No. ({id}) added successfully and print command sent.',
      'pb_save_server_fail': 'Failed to save invoice on server: ',
      'pb_network_error': 'Network error: ',
      'pb_sales_offer_invoice': 'Sales Offer Invoice',
      'pb_purchase_offer_invoice': 'Purchase Offer Invoice',
      'pb_partner_name': 'Partner: ',
      'pb_scan_tooltip': 'Scan barcode with camera',
      'pb_items_in_cart': 'Items in Cart: ',
      'pb_total_kd': 'Total: {total}',
      'pb_search_hint': 'Search by product name or barcode...',
      'pb_barcode_hint': 'Enter barcode...',
      'pb_approved_items_title': 'Approved Items and Prices in Partner Offer:',
      'pb_no_barcode': 'No Barcode',
      'pb_cart_title': 'Shopping Cart / Current Invoice',
      'pb_cart_empty': 'Cart is empty\nTap on items to add them',
      'pb_item_price': 'Price: ',
      'pb_item_quantity': ' | Qty: ',
      'pb_subtotal': 'Subtotal:',
      'pb_discount_value': 'Discount:',
      'pb_net_amount': 'Net Amount:',
      'pb_pay_cash': 'Pay Cash (F12)',
      'pb_pay_credit': 'Pay Credit',
      'pb_no_results': 'No matching results found',
      'pb_add_btn': 'Add',
      'pb_view_cart': 'View Cart ({count})',
      'pb_current_cart': 'Current Cart Contents:',
      'pb_empty_cart_short': 'Cart is empty',
      'pb_final_net': 'Final Net Total: {total}',
      // Payment Voucher Screen
      'pv_offline_error': 'You are offline. You can enter a free payment.',
      'pv_supplier_required': 'Please select a supplier first',
      'pv_invoice_or_free_required':
          'Please select at least one invoice or enter a free payment amount',
      'pv_account_required': 'Please select a payment account',
      'pv_no_shift_open': 'No open shift found',
      'pv_confirm_title': 'Confirm Payment Voucher',
      'pv_confirm_desc':
          'A payment voucher will be recorded with the amount of\n{amount}\nfor Supplier: {partner}',
      'pv_cancel': 'Cancel',
      'pv_confirm': 'Confirm',
      'pv_default_desc': 'Payment Voucher - ',
      'pv_save_print_success':
          'Voucher No. ({id}) saved and printed successfully',
      'pv_save_error': 'Unexpected error: ',
      'pv_screen_title': 'Payment Voucher',
      'pv_supplier_label': 'Supplier: ',
      'pv_search_hint': 'Search supplier by name or phone...',
      'pv_no_suppliers': 'No suppliers found',
      'pv_no_dues': 'No dues for this supplier',
      'pv_account_label': 'Payment Account',
      'pv_note_hint': 'Note (optional)...',
      'pv_no_invoices':
          'No invoices (or offline).\nYou can enter a free payment (account payment).',
      'pv_free_payment_label': 'Free Payment Amount (Account Payment)',
      'pv_purchase_invoice_label': 'Purchase Invoice #',
      'pv_total_label': 'Total: ',
      'pv_remainder_label': 'Remainder: {amount}',
      'pv_payment_amount_label': 'Payment Amount: ',
      'pv_selected_invoices': '{count} Selected Invoices',
      'pv_submit_button': 'Record Payment',
      // Receipt Voucher Screen
      'rv_offline_error':
          'You are offline. Cannot fetch invoices. Please enter a free payment amount.',
      'rv_customer_required': 'Please select a customer first',
      'rv_invoice_or_free_required':
          'Please select at least one invoice or enter a free payment amount',
      'rv_account_required': 'Please select a receipt account',
      'rv_no_shift_open': 'No open shift found',
      'rv_confirm_title': 'Confirm Receipt Voucher',
      'rv_confirm_desc':
          'A receipt voucher will be recorded with the amount of\n{amount}\nfrom Customer: {partner}',
      'rv_cancel': 'Cancel',
      'rv_confirm': 'Confirm',
      'rv_default_desc': 'Receipt Voucher - ',
      'rv_save_print_success':
          'Voucher No. ({id}) saved and printed successfully',
      'rv_save_error': 'Unexpected error: ',
      'rv_screen_title': 'Receipt Voucher',
      'rv_customer_label': 'Customer: ',
      'rv_search_hint': 'Search customer by name or phone...',
      'rv_no_customers': 'No customers found',
      'rv_no_dues': 'No dues for this customer',
      'rv_account_label': 'Receipt Account',
      'rv_note_hint': 'Note (optional)...',
      'rv_no_invoices':
          'Cannot fetch invoices (or none exist).\nYou can enter a free payment (account payment).',
      'rv_free_payment_label': 'Free Payment Amount (Account Payment)',
      'rv_sales_invoice_label': 'Invoice #',
      'rv_total_label': 'Total: ',
      'rv_remainder_label': 'Remainder: {amount}',
      'rv_receipt_amount_label': 'Receipt Amount: ',
      'rv_selected_invoices': '{count} Selected Invoices',
      'rv_submit_button': 'Record Receipt',
      // General Payment Voucher Screen
      'gpv_choose_expense_account': 'Choose Expense Account',
      'gpv_search_account_hint': 'Search for an account...',
      'gpv_account_code': 'Code: {code}',
      'gpv_expense_account_required':
          'Please select the target account (Expenses)',
      'gpv_amount_required': 'Please enter the amount',
      'gpv_invalid_amount': 'Invalid amount',
      'gpv_cash_account_required': 'Please select the cash/bank account',
      'gpv_undefined': 'Undefined',
      'gpv_cash': 'Cash',
      'gpv_save_print_success':
          'Payment voucher created and printed successfully (No. {id})',
      'gpv_save_error': 'Error during saving: ',
      'gpv_cannot_save': 'Cannot save: ',
      'gpv_screen_title': 'Direct Payment Voucher (Expenses)',
      'gpv_target_account_label': 'Target Account (Expense)',
      'gpv_click_to_choose': 'Tap to choose account',
      'gpv_amount_label': 'Amount ',
      'gpv_statement_label': 'Statement / Notes',
      'gpv_pay_from_account': 'Pay from account (Cashier)',
      'gpv_save_button': 'Save Direct Voucher',
      // General Receipt Voucher Screen
      'grv_choose_revenue_account': 'Choose Revenue Account',
      'grv_revenue_account_required':
          'Please select the target account (Revenues)',
      'grv_save_print_success':
          'Receipt voucher created and printed successfully (No. {id})',
      'grv_screen_title': 'Direct Receipt Voucher (Revenues)',
      'grv_target_account_label': 'Target Account (Revenue)',
      'grv_receive_to_account': 'Receive to Account (Cash)',
      'grv_save_button': 'Save Direct Voucher',
      // Daily Invoices Screen
      'di_fetch_error': 'Failed to retrieve today\'s invoices from server',
      'di_error_loading': 'Error loading invoices: {error}',
      'di_screen_title': 'Daily Invoices & User Report',
      'di_total_sales': 'Total Sales',
      'di_total_purchases': 'Total Purchases',
      'di_net_income': 'Net Income (Sales - Purchases)',
      'di_total_receipts': 'Receipt Vouchers (In)',
      'di_total_payments': 'Payment Vouchers (Out)',
      'di_net_cash': 'Net Cash (Drawer)',
      'di_tab_sales': 'Sales',
      'di_tab_purchases': 'Purchases',
      'di_tab_receipts': 'Receipts',
      'di_tab_payments': 'Payments',
      'di_sales_invoices': 'Daily Customer Sales',
      'di_purchase_invoices': 'Daily Supplier Purchases',
      'di_receipt_vouchers': 'Receipt Vouchers (Collections)',
      'di_payment_vouchers': 'Payment Vouchers (Expenses)',
      'di_daily_financial_split': 'Daily Financial Split',
      'di_shift_financial_vouchers': 'Shift Financial Vouchers',
      'di_no_invoices': 'No data available',
      'di_invoice_no': 'Invoice No: #{id}',
      'di_date': 'Date: {date}',
      'di_time': 'Time: {time}',
      'di_net_amount': 'Net: {amount}',
      'di_voucher_no': 'Voucher No: #{id}',
      'di_voucher_amount': 'Amount: {amount}',
      'di_voucher_desc': 'Statement: {desc}',
      'di_print_button': 'Print Details',
      'di_print_success': 'Invoice printed successfully',
      'di_print_error': 'Failed to print invoice',
      'di_invoice_details': 'Invoice Details',
      'di_partner_name': 'Customer/Supplier: {name}',
      'di_discount': 'Discount: {amount}',
      'di_paid': 'Paid: {amount}',
      'di_remainder': 'Remainder: {amount}',
      'di_cashier': 'Cashier: {name}',
      'di_invoice_items': 'Invoice Items:',
      'di_item_details':
          '{name}  -  Qty: {qty}  -  Price: {price}  -  Total: {total}',
      'di_total_col': 'Total',
      'di_price_col': 'Price',
      'di_qty_col': 'Qty',
      'di_item_col': 'Item',
      'di_grand_total': 'Grand Total',
      'di_net_total': 'Net Total',
      'di_register_payment': 'Record Payment',
      'di_reprint': 'Reprint',
      'di_close_popup': 'Close',
      'di_payment_dialog_title': 'Record Credit Invoice Payment',
      'di_payment_remaining': 'Remaining Unpaid: {amount}',
      'di_payment_amount_label': 'Payment Amount Received',
      'di_payment_account_label': 'Payment Method (Account)',
      'di_split_total_paid': 'Total Split Paid:',
      'di_payment_method_label': 'Payment Method',
      'di_payment_amount_single': 'Amount',
      'di_add_payment_method_btn': 'Add Another Payment Method',
      'di_invalid_split_amounts':
          'Please enter valid amounts for payment methods',
      'di_single_payment_mode': 'Single Payment',
      'di_cancel': 'Cancel',
      'di_confirm_payment': 'Confirm Payment',
      'print_payment_methods': 'Payment Methods',
      'print_payment_method': 'Payment Method',
      'print_payment_cash': 'Cash',
      'print_payment_credit': 'Credit',
      'print_payment_cash_credit': 'Cash + Credit',
      'print_total_paid': 'Total Paid',
      'print_balance_due': 'Balance Due',
      'print_payment_breakdown': 'Payment Methods Breakdown:',
      'di_invalid_payment':
          'Please enter a valid amount not exceeding the remainder',
      'di_payment_success': 'Payment recorded and accounting entries updated!',
      'di_payment_fail': 'Failed to record payment: {error}',
      'di_payment_error': 'Error during payment: {error}',
      'di_fetch_fail': 'Failed to fetch invoice details from server',
      'di_network_error': 'Network error: {error}',
      // Close Shift Screen
      'cs_summary_fetch_error':
          'Failed to fetch shift summary. Make sure a shift is open.',
      'cs_data_load_error': 'Error loading data: {error}',
      'cs_enter_actual_cash': 'Please enter actual cash first',
      'cs_offline_data_warning':
          'Please ensure internet connection and save all offline data before closing the shift.',
      'cs_confirm_close_title': 'Confirm Close Shift',
      'cs_confirm_close_msg':
          'Are you sure you want to close the current shift?\nThis action cannot be undone.',
      'cs_cancel': 'Cancel',
      'cs_close_shift': 'Close Shift',
      'cs_success': 'Success',
      'cs_close_success_msg': 'Shift closed successfully.',
      'cs_ok': 'OK',
      'cs_error': 'Error',
      'cs_close_error_msg': 'Error closing shift: {error}',
      'cs_screen_title': 'Close Shift & Handover Cash',
      'cs_financial_summary': 'Shift Financial Summary',
      'cs_starting_cash': 'Starting Cash',
      'cs_total_paid_sales': 'Total Paid Sales',
      'cs_total_paid_purchases': 'Total Paid Purchases',
      'cs_total_receipts': 'Total Receipt Vouchers',
      'cs_total_payments': 'Total Payment Vouchers',
      'cs_expected_cash': 'Expected Total Cash',
      'cs_actual_cash': 'Actual Cash (in drawer)',
      'cs_enter_actual_cash_hint': 'Enter actual cash here',
      'cs_difference': 'Deficit / Surplus',
      'cs_close_print_btn': 'Close & Print Report',
      'cs_unsynced_data_title': 'Unsynced Data',
      'cs_unsynced_data_msg':
          'There are {invoices} invoices and {vouchers} vouchers unsynced.\nThey must be synced before closing the shift.',
      'cs_sync_now': 'Sync Now',
      'cs_sync_failed':
          'Failed to sync some data. Please check your internet connection.',
      'cs_sync_success': 'Synced successfully.',
      'cs_entered_cash': 'Entered Closing Cash: {amount}',
      'cs_expected_cash_msg': 'Expected Cash: {amount}',
      'cs_difference_msg': 'Difference: {amount}',
      'cs_confirm_close_with_print_msg':
          'Are you sure you want to close the shift?\nA daily report will be printed before closing.',
      'cs_yes_close_shift': 'Yes, Close Shift',
      'cs_printing': 'Printing...',
      'cs_closed_successfully': 'Closed successfully',
      'cs_closing': 'Closing...',
      'cs_printer_error': 'Failed to connect to printer',
      'cs_cashier': 'Cashier',
      'cs_open_time': 'Open Time',
      'cs_status': 'Status',
      'cs_sales_summary': '📈 Shift Sales',
      'cs_invoice_count': '{count} Invoices',
      'cs_total_sales_label': 'Total Sales',
      'cs_paid_sales_label': 'Paid in Cash',
      'cs_cash_sales_label': 'Cash Sales',
      'cs_knet_sales_label': 'Card / K-Net Sales',
      'cs_credit_sales_label': 'Remaining Credit',
      'cs_purchases_summary': '📦 Shift Purchases',
      'cs_total_purchases_label': 'Total Purchases',
      'cs_paid_purchases_label': 'Paid in Cash',
      'cs_cash_purchases_label': 'Cash Purchases',
      'cs_non_cash_purchases_label': 'Non-Cash Purchases',
      'cs_credit_purchases_label': 'Remaining Credit',
      'cs_cash_drawer_calc': '💰 Cash Drawer Settlement',
      'cs_add_cash_sales': '(+) Cash Sales Collected',
      'cs_sub_cash_purchases': '(-) Cash Purchases Paid',
      'cs_add_receipts': '(+) Receipt Vouchers',
      'cs_subtract_payments': '(-) Payment Vouchers',
      'cs_loading_summary': 'Loading shift summary...',
      'cs_retry': 'Retry',
      'cs_shift_info': '📋 Shift Information',
      'cs_invoices_count': 'Invoices Count',
      'cs_vouchers_summary': '🧾 Financial Vouchers',
      'cs_add_paid_sales': '(+) Cash Sales Collected',
      'cs_sub_paid_purchases': '(-) Cash Purchases Paid',
      'cs_sub_payments': '(-) Payment Vouchers',
      // In-App Auto Update Dialog
      'update_title': 'New Update Available!',
      'update_version_label': 'Version:',
      'update_current_label': 'Current:',
      'update_whats_new': 'What\'s New in this Update:',
      'update_default_notes': '• General performance enhancements, stability, and speed improvements.',
      'update_now_btn': 'Update Now ⚡',
      'update_later_btn': 'Later',
      'update_downloading_connecting': 'Connecting to server and downloading update...',
      'update_downloading_progress': 'Downloading:',
      'update_download_completed': 'Download completed 100%! Launching installer... 🚀',
      'update_installer_opened': 'Installer launched! Please confirm installation on your screen.',
      'update_install_failed': 'Could not launch automatic installer.',
      'update_install_permission_warn': 'Please make sure to allow installing apps from this source in device settings.',
      'update_already_latest': 'You are already using the latest version of the app! 🎉',
      'settings_check_updates': 'Check for Updates',
      'settings_check_updates_desc': 'Check server for newer app versions',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// Extension for easier translation
extension TranslateExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
