; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "OmanApp"
#define MyAppVersion "2.1.3.0"
#define MyAppPublisher "Mohamed Ragab"
#define MyAppURL "www.mohamedRagab.com"
#define MyAppExeName "Vegtablity.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A760CC7E-3358-4684-A9D1-E1D8AB395E27}
AppName="OmanApp"
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\VB.NET\backup\Vegtablity\setup\Output
OutputBaseFilename=Oman_SetupV2.1.3
SetupIconFile=D:\VB.NET\backup\Vegtablity\Vegtablity\lettuce.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\VB.NET\backup\Vegtablity\TenantConfigs\dbconfig_OmanCustmerDB.dat"; DestDir: "{app}"; DestName: "dbconfig.dat"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\ClosedXML.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\Dapper.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\ExcelNumberFormat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\Irony.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\LiveCharts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\LiveCharts.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\LiveCharts.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\LiveCharts.Wpf.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\PdfSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\PdfSharp.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\SixLabors.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\System.CodeDom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\System.IO.Packaging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\Vegtablity.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\Vegtablity.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\Vegtablity.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\Vegtablity.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\VB.NET\backup\Vegtablity\Vegtablity\Vegtablity\bin\Release\XLParser.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

